/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.guina.rel;

import com.guina.uteis.uteis;
import com.guina.view.FrmCliLojas020;
import java.io.File;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author SUPORTE
 */
public class RelatorioCliente extends javax.swing.JFrame {

    /**
     * Creates new form RelatorioCliente
     */
    public RelatorioCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        em = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("permissaoPU").createEntityManager();
        queryCliLoja = java.beans.Beans.isDesignTime() ? null : em.createQuery("SELECT t FROM Tb020clienteLojas t");
        listCliLoja = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(queryCliLoja.getResultList());
        masterScrollPane = new javax.swing.JScrollPane();
        tbCliLojas = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        txtPesq = new javax.swing.JTextField();
        btnPdf = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Relatorio Cliente");

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, listCliLoja, tbCliLojas);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nomeCli}"));
        columnBinding.setColumnName("Nome");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${emailCli}"));
        columnBinding.setColumnName("Email");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${celCli}"));
        columnBinding.setColumnName("Celular");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        tbCliLojas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbCliLojasMouseClicked(evt);
            }
        });
        masterScrollPane.setViewportView(tbCliLojas);
        if (tbCliLojas.getColumnModel().getColumnCount() > 0) {
            tbCliLojas.getColumnModel().getColumn(0).setMinWidth(250);
            tbCliLojas.getColumnModel().getColumn(0).setMaxWidth(300);
            tbCliLojas.getColumnModel().getColumn(1).setMinWidth(200);
            tbCliLojas.getColumnModel().getColumn(1).setMaxWidth(250);
            tbCliLojas.getColumnModel().getColumn(2).setMinWidth(80);
            tbCliLojas.getColumnModel().getColumn(2).setMaxWidth(100);
        }

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Pesquisa...", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));
        jPanel4.setLayout(new java.awt.GridLayout());

        txtPesq.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesqKeyReleased(evt);
            }
        });
        jPanel4.add(txtPesq);

        btnPdf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/guina/icone/pdf.png"))); // NOI18N
        btnPdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPdfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(masterScrollPane)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 697, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPdf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPdf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(masterScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );

        bindingGroup.bind();

        setSize(new java.awt.Dimension(771, 484));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tbCliLojasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbCliLojasMouseClicked
   //     acao = ("Alterar");           // TODO add your handling code here:
    }//GEN-LAST:event_tbCliLojasMouseClicked

    private void txtPesqKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesqKeyReleased
        uteis.maiscula(evt);
        queryCliLoja = em.createQuery("SELECT t FROM Tb020clienteLojas t WHERE t.nomeCli like :nome ");
        queryCliLoja.setParameter("nome", "%" + txtPesq.getText() + "%");
        listCliLoja.clear();
        listCliLoja.addAll(queryCliLoja.getResultList());  // TODO add your handling code here:
    }//GEN-LAST:event_txtPesqKeyReleased

    private void btnPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPdfActionPerformed
        String url = new File("Cliente.jrxml").getAbsolutePath();
        try {
            JasperReport rel = JasperCompileManager.compileReport(url);
            JRBeanCollectionDataSource jrbcds = new JRBeanCollectionDataSource(listCliLoja, false);
      //     JRBeanCollectionDataSource dados = new JRBeanCollectionDataSource(listCliLoja,false);
            JasperPrint print = JasperFillManager.fillReport(rel,new HashMap(),jrbcds);
            JasperViewer view = new JasperViewer(print,false);
            view.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(RelatorioCliente.class.getName()).log(Level.SEVERE,null,ex);
        }

        /*  try {
            JRResultSetDataSource dados = new JRResultSetDataSource((ResultSet) listFicha);
            InputStream url = this.getClass().getClassLoader().getResourceAsStream("Relatorio/SisCons.jrxml");
            JasperPrint print = JasperFillManager.fillReport(url, new HashMap(), dados);
            JasperExportManager.exportReportToPdfFile(print,"C:/Users/SUPORTE/Documents/NetBeansProjects/controlpermissao/rel/conserto.pdf");

            File file = new File("C:/Users/SUPORTE/Documents/NetBeansProjects/controlpermissao/rel/conserto.pdf");
            try {
                Desktop.getDesktop().open(file);
            } catch (Exception e) {
                JOptionPane.showConfirmDialog(null, e);
            }
            file.deleteOnExit();

        } catch (Exception e){
        }*/

        //
        //         try {
            //            String caminho = new File("SisCons.jrxml").getAbsolutePath();
            //            JasperReport rel = JasperCompileManager.compileReport(caminho);
            //
            //            JRResultSetDataSource dados = new JRResultSetDataSource(listFicha,false);
            //            JasperPrint print = JasperFillManager.fillReport(rel, new HashMap(), dados);
            //            JasperViewer view = new JasperViewer(print);
            //            view.setVisible(true);
            //            view.setAlwaysOnTop(true);
            //        } catch (Exception ex) {
            //            Logger.getLogger(FrmFichaConsT019.class.getName()).log(Level.SEVERE, null, ex);
            //        }

        /* String src = "Relatorio/SisCons.jasper";
        JasperPrint jp = null;
        try {
            jp = JasperFillManager.fillReport(src,null);
        } catch (Exception e) {
            System.out.println("Error: "+e);
        }
        JasperViewer view = new JasperViewer(jp,false);
        view.setVisible(true); */
    }//GEN-LAST:event_btnPdfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RelatorioCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RelatorioCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RelatorioCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelatorioCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RelatorioCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPdf;
    private javax.persistence.EntityManager em;
    private javax.swing.JPanel jPanel4;
    private java.util.List<com.guina.model.Tb020clienteLojas> listCliLoja;
    private javax.swing.JScrollPane masterScrollPane;
    private javax.persistence.Query queryCliLoja;
    public javax.swing.JTable tbCliLojas;
    public javax.swing.JTextField txtPesq;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
