/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.guina.view;

import com.guina.uteis.uteis;
import java.beans.Beans;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.RollbackException;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Agnaldo
 */
public class frmLogTb010 extends javax.swing.JDialog {

    /**
     * Creates new form frmLogTb010
     */
    public frmLogTb010(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        if (!Beans.isDesignTime()) {
            em.getTransaction().begin();
        }
        //ORGANIZAR TABELA MODO CRESCENTE OU DECRESCENTE - TABELA DE ITENS
        TableModel modelo = (TableModel) tbLog.getModel();
        tbLog.setRowSorter(new TableRowSorter(modelo));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        em = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("permissaoPU").createEntityManager();
        query = java.beans.Beans.isDesignTime() ? null : em.createQuery("SELECT t FROM Tb010logsistema t");
        list = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(query.getResultList());
        jPanel2 = new javax.swing.JPanel();
        btnSalvar = new javax.swing.JButton();
        btnIncluir = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnCancela = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        usuerlogLabel = new javax.swing.JLabel();
        usuerlogField = new javax.swing.JTextField();
        iditemlogLabel = new javax.swing.JLabel();
        datalogoLabel = new javax.swing.JLabel();
        idlogLabel = new javax.swing.JLabel();
        tablogField = new javax.swing.JTextField();
        horalogLabel = new javax.swing.JLabel();
        iditemlogField = new javax.swing.JTextField();
        tablogLabel = new javax.swing.JLabel();
        acaologLabel = new javax.swing.JLabel();
        idlogField = new javax.swing.JTextField();
        horalogField = new javax.swing.JTextField();
        itemnomelogField = new javax.swing.JTextField();
        datalogoField = new javax.swing.JTextField();
        acaologField = new javax.swing.JTextField();
        itemnomelogLabel = new javax.swing.JLabel();
        masterScrollPane = new javax.swing.JScrollPane();
        tbLog = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        txtPesq = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        txtPesqItem = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("LOG SISTEMA");
        setResizable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        btnSalvar.setText("Save");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        jPanel2.add(btnSalvar);

        btnIncluir.setText("New");
        btnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirActionPerformed(evt);
            }
        });
        jPanel2.add(btnIncluir);

        btnExcluir.setText("Delete");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        jPanel2.add(btnExcluir);

        btnCancela.setText("Refresh");
        btnCancela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelaActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancela);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        usuerlogLabel.setText("Usuario:");

        usuerlogField.setEditable(false);
        usuerlogField.setBackground(new java.awt.Color(153, 204, 255));
        usuerlogField.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tbLog, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.usuerlog}"), usuerlogField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        iditemlogLabel.setText("ID Item:");

        datalogoLabel.setText("Data:");

        idlogLabel.setText("ID");

        tablogField.setEditable(false);
        tablogField.setBackground(new java.awt.Color(153, 204, 255));
        tablogField.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tbLog, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.tablog}"), tablogField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        horalogLabel.setText("Hora:");

        iditemlogField.setEditable(false);
        iditemlogField.setBackground(new java.awt.Color(153, 204, 255));
        iditemlogField.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tbLog, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.iditemlog}"), iditemlogField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        tablogLabel.setText("Tabela:");

        acaologLabel.setText("Ação:");

        idlogField.setEditable(false);
        idlogField.setBackground(new java.awt.Color(153, 204, 255));
        idlogField.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tbLog, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.idlog}"), idlogField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        horalogField.setEditable(false);
        horalogField.setBackground(new java.awt.Color(153, 204, 255));
        horalogField.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tbLog, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.horalog}"), horalogField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        itemnomelogField.setEditable(false);
        itemnomelogField.setBackground(new java.awt.Color(153, 204, 255));
        itemnomelogField.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tbLog, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.itemnomelog}"), itemnomelogField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        datalogoField.setEditable(false);
        datalogoField.setBackground(new java.awt.Color(153, 204, 255));
        datalogoField.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tbLog, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.datalogo}"), datalogoField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        acaologField.setEditable(false);
        acaologField.setBackground(new java.awt.Color(153, 204, 255));
        acaologField.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tbLog, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.acaolog}"), acaologField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        itemnomelogLabel.setText("Item:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idlogLabel)
                    .addComponent(datalogoLabel)
                    .addComponent(horalogLabel)
                    .addComponent(usuerlogLabel)
                    .addComponent(tablogLabel)
                    .addComponent(acaologLabel)
                    .addComponent(iditemlogLabel)
                    .addComponent(itemnomelogLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(idlogField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acaologField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                    .addComponent(tablogField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usuerlogField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(horalogField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(datalogoField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iditemlogField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemnomelogField, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idlogLabel)
                    .addComponent(idlogField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(datalogoLabel)
                    .addComponent(datalogoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(horalogLabel)
                    .addComponent(horalogField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usuerlogLabel)
                    .addComponent(usuerlogField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tablogLabel)
                    .addComponent(tablogField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acaologLabel)
                    .addComponent(acaologField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iditemlogLabel)
                    .addComponent(iditemlogField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemnomelogLabel)
                    .addComponent(itemnomelogField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, list, tbLog);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${datalogo}"));
        columnBinding.setColumnName("DATA");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${horalog}"));
        columnBinding.setColumnName("HORA");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${usuerlog}"));
        columnBinding.setColumnName("USUARIO");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${tablog}"));
        columnBinding.setColumnName("TABELA");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${acaolog}"));
        columnBinding.setColumnName("AÇÃO");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${iditemlog}"));
        columnBinding.setColumnName("ID ITEM");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${itemnomelog}"));
        columnBinding.setColumnName("ITEM");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${idlog}"));
        columnBinding.setColumnName("Idlog");
        columnBinding.setColumnClass(Integer.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        masterScrollPane.setViewportView(tbLog);
        if (tbLog.getColumnModel().getColumnCount() > 0) {
            tbLog.getColumnModel().getColumn(0).setMinWidth(60);
            tbLog.getColumnModel().getColumn(0).setMaxWidth(80);
            tbLog.getColumnModel().getColumn(1).setMinWidth(60);
            tbLog.getColumnModel().getColumn(1).setMaxWidth(80);
            tbLog.getColumnModel().getColumn(2).setMinWidth(140);
            tbLog.getColumnModel().getColumn(2).setMaxWidth(200);
            tbLog.getColumnModel().getColumn(3).setMinWidth(100);
            tbLog.getColumnModel().getColumn(3).setMaxWidth(110);
            tbLog.getColumnModel().getColumn(4).setMinWidth(90);
            tbLog.getColumnModel().getColumn(4).setMaxWidth(110);
            tbLog.getColumnModel().getColumn(5).setMinWidth(40);
            tbLog.getColumnModel().getColumn(5).setMaxWidth(50);
            tbLog.getColumnModel().getColumn(6).setMinWidth(200);
            tbLog.getColumnModel().getColumn(6).setMaxWidth(210);
            tbLog.getColumnModel().getColumn(7).setMinWidth(1);
            tbLog.getColumnModel().getColumn(7).setMaxWidth(1);
        }

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Pesquisa Tabela", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));
        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        txtPesq.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesqKeyReleased(evt);
            }
        });
        jPanel4.add(txtPesq);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Pesquisa Item", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));
        jPanel5.setLayout(new java.awt.GridLayout(1, 0));

        txtPesqItem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesqItemKeyReleased(evt);
            }
        });
        jPanel5.add(txtPesqItem);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(masterScrollPane)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 97, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(masterScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 32, Short.MAX_VALUE)))
                .addContainerGap())
        );

        bindingGroup.bind();

        setSize(new java.awt.Dimension(1080, 358));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        try {
            em.getTransaction().commit();
            em.getTransaction().begin();
        } catch (RollbackException rex) {
            rex.printStackTrace();
            em.getTransaction().begin();
            List<com.guina.model.Tb010logsistema> merged = new ArrayList<com.guina.model.Tb010logsistema>(list.size());
            for (com.guina.model.Tb010logsistema t : list) {
                merged.add(em.merge(t));
            }
            list.clear();
            list.addAll(merged);
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirActionPerformed
        com.guina.model.Tb010logsistema t = new com.guina.model.Tb010logsistema();
        em.persist(t);
        list.add(t);
        int row = list.size() - 1;
        tbLog.setRowSelectionInterval(row, row);
        tbLog.scrollRectToVisible(tbLog.getCellRect(row, 0, true));
    }//GEN-LAST:event_btnIncluirActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int[] selected = tbLog.getSelectedRows();
        List<com.guina.model.Tb010logsistema> toRemove = new ArrayList<com.guina.model.Tb010logsistema>(selected.length);
        for (int idx = 0; idx < selected.length; idx++) {
            com.guina.model.Tb010logsistema t = list.get(tbLog.convertRowIndexToModel(selected[idx]));
            toRemove.add(t);
            em.remove(t);
        }
        list.removeAll(toRemove);
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnCancelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelaActionPerformed
        em.getTransaction().rollback();
        em.getTransaction().begin();
        java.util.Collection data = query.getResultList();
        for (Object entity : data) {
            em.refresh(entity);
        }
        list.clear();
        list.addAll(data);
    }//GEN-LAST:event_btnCancelaActionPerformed

    private void txtPesqKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesqKeyReleased
//        uteis.maiscula(evt);
        query = em.createQuery("SELECT t FROM Tb010logsistema t WHERE t.tablog like :nome");
        query.setParameter("nome", "%" + txtPesq.getText() + "%");
        list.clear();
        list.addAll(query.getResultList());        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesqKeyReleased

    private void txtPesqItemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesqItemKeyReleased
         uteis.maiscula(evt);
        query = em.createQuery("SELECT t FROM Tb010logsistema t WHERE t.itemnomelog like :nome");
        query.setParameter("nome", "%" + txtPesqItem.getText() + "%");
        list.clear();
        list.addAll(query.getResultList());  // TODO add your handling code here:
    }//GEN-LAST:event_txtPesqItemKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows Classic".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLogTb010.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLogTb010.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLogTb010.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLogTb010.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmLogTb010 dialog = new frmLogTb010(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField acaologField;
    private javax.swing.JLabel acaologLabel;
    public javax.swing.JButton btnCancela;
    public javax.swing.JButton btnExcluir;
    public javax.swing.JButton btnIncluir;
    public javax.swing.JButton btnSalvar;
    private javax.swing.JTextField datalogoField;
    private javax.swing.JLabel datalogoLabel;
    private javax.persistence.EntityManager em;
    private javax.swing.JTextField horalogField;
    private javax.swing.JLabel horalogLabel;
    private javax.swing.JTextField iditemlogField;
    private javax.swing.JLabel iditemlogLabel;
    private javax.swing.JTextField idlogField;
    private javax.swing.JLabel idlogLabel;
    private javax.swing.JTextField itemnomelogField;
    private javax.swing.JLabel itemnomelogLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private java.util.List<com.guina.model.Tb010logsistema> list;
    private javax.swing.JScrollPane masterScrollPane;
    private javax.persistence.Query query;
    private javax.swing.JTextField tablogField;
    private javax.swing.JLabel tablogLabel;
    public javax.swing.JTable tbLog;
    public javax.swing.JTextField txtPesq;
    public javax.swing.JTextField txtPesqItem;
    private javax.swing.JTextField usuerlogField;
    private javax.swing.JLabel usuerlogLabel;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
