/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.guina.view;

import com.guina.consulta.frmConsMarcaTb006;
import com.guina.model.Tb001user;
import com.guina.model.Tb006marcas;
import com.guina.uteis.uteis;
import java.beans.Beans;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.RollbackException;
import javax.swing.JFrame;

/**
 *
 * @author Agnaldo
 */
public class frmModeloTb007 extends javax.swing.JDialog {
    //nome da tabela////////

    String tb = "tb007modelo"; //id 8
    String acao;

    /////////////////////////
    /**
     * Creates new form frmModeloTb007
     */
    public frmModeloTb007(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        if (!Beans.isDesignTime()) {
            em.getTransaction().begin();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        em = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("permissaoPU").createEntityManager();
        query = java.beans.Beans.isDesignTime() ? null : em.createQuery("SELECT t FROM Tb007modelos t");
        list = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(query.getResultList());
        queryMarca = java.beans.Beans.isDesignTime() ? null : em.createQuery("SELECT t FROM Tb006marcas t");
        listMarca = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(queryMarca.getResultList());
        queryLog = java.beans.Beans.isDesignTime() ? null : em.createQuery("SELECT t FROM Tb010logsistema t");
        listLog = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(queryLog.getResultList());
        queryUser = java.beans.Beans.isDesignTime() ? null : em.createQuery("SELECT t FROM Tb001user t");
        listUser = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(queryUser.getResultList());
        jpDados = new javax.swing.JPanel();
        nomemodeloLabel = new javax.swing.JLabel();
        datacadmodeloLabel = new javax.swing.JLabel();
        idmodeloLabel = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        marcamodelotb006Label = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jcMarca = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jpBotoes = new javax.swing.JPanel();
        btnIncluir = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnCancela = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        masterScrollPane = new javax.swing.JScrollPane();
        tbModelo = new javax.swing.JTable();
        jpFormLog = new javax.swing.JPanel();
        txtIdItem = new javax.swing.JTextField();
        txtItem = new javax.swing.JTextField();
        txtUser = new javax.swing.JTextField();
        txtData = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtHora = new javax.swing.JTextField();
        txtAcao = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ITEM = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        masterScrollPane1 = new javax.swing.JScrollPane();
        tbLog = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnSalvarLog = new javax.swing.JButton();
        btnCancelaLog = new javax.swing.JButton();
        btnNovoLog = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtTabela = new javax.swing.JTextField();
        jpPesquisa = new javax.swing.JPanel();
        txtPesq = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Modelo");
        setResizable(false);

        jpDados.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        nomemodeloLabel.setText("Modelo:");

        datacadmodeloLabel.setText("Data:");

        idmodeloLabel.setText("ID:");

        txtId.setEditable(false);
        txtId.setBackground(new java.awt.Color(255, 255, 204));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tbModelo, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.idmodelo}"), txtId, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tbModelo, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), txtId, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        marcamodelotb006Label.setText("Marca");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tbModelo, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.nomemodelo}"), txtNome, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tbModelo, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), txtNome, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        txtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNomeKeyReleased(evt);
            }
        });

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tbModelo, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.datacadmodelo}"), jDateChooser1, org.jdesktop.beansbinding.BeanProperty.create("date"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tbModelo, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), jDateChooser1, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, listMarca, jcMarca);
        bindingGroup.addBinding(jComboBoxBinding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tbModelo, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.marcamodelotb006}"), jcMarca, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tbModelo, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), jcMarca, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        jButton1.setText("...");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tbModelo, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), jButton1, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpDadosLayout = new javax.swing.GroupLayout(jpDados);
        jpDados.setLayout(jpDadosLayout);
        jpDadosLayout.setHorizontalGroup(
            jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idmodeloLabel)
                    .addComponent(nomemodeloLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpDadosLayout.createSequentialGroup()
                        .addComponent(marcamodelotb006Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpDadosLayout.createSequentialGroup()
                        .addComponent(datacadmodeloLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpDadosLayout.setVerticalGroup(
            jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(idmodeloLabel)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(datacadmodeloLabel))
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomemodeloLabel)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(marcamodelotb006Label)
                    .addComponent(jcMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(61, 61, 61))
        );

        jpBotoes.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jpBotoes.setLayout(new java.awt.GridLayout(1, 0));

        btnIncluir.setText("Novo");
        btnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirActionPerformed(evt);
            }
        });
        jpBotoes.add(btnIncluir);

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        jpBotoes.add(btnSalvar);

        btnCancela.setText("Cancela");
        btnCancela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelaActionPerformed(evt);
            }
        });
        jpBotoes.add(btnCancela);

        btnExcluir.setText("Delete");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        jpBotoes.add(btnExcluir);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, list, tbModelo);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${idmodelo}"));
        columnBinding.setColumnName("ID");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${datacadmodelo}"));
        columnBinding.setColumnName("Data");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nomemodelo}"));
        columnBinding.setColumnName("Modelo");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${marcamodelotb006}"));
        columnBinding.setColumnName("Marca");
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        tbModelo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbModeloMouseClicked(evt);
            }
        });
        masterScrollPane.setViewportView(tbModelo);
        if (tbModelo.getColumnModel().getColumnCount() > 0) {
            tbModelo.getColumnModel().getColumn(0).setMinWidth(25);
            tbModelo.getColumnModel().getColumn(0).setMaxWidth(35);
            tbModelo.getColumnModel().getColumn(1).setMinWidth(70);
            tbModelo.getColumnModel().getColumn(1).setMaxWidth(90);
            tbModelo.getColumnModel().getColumn(2).setMinWidth(80);
            tbModelo.getColumnModel().getColumn(2).setMaxWidth(110);
            tbModelo.getColumnModel().getColumn(3).setMinWidth(90);
            tbModelo.getColumnModel().getColumn(3).setMaxWidth(120);
        }

        jpFormLog.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Log"));

        txtIdItem.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tbLog, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.iditemlog}"), txtIdItem, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        txtItem.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tbLog, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.itemnomelog}"), txtItem, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        txtUser.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tbLog, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.usuerlog}"), txtUser, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        txtUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUserFocusGained(evt);
            }
        });

        txtData.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tbLog, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.datalogo}"), txtData, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        txtUsuario.setText("jLabel6");

        jLabel1.setText("USER:");

        jLabel5.setText("AÇÃO");

        txtHora.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tbLog, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.horalog}"), txtHora, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        txtAcao.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tbLog, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.acaolog}"), txtAcao, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jLabel2.setText("DATA:");

        ITEM.setText("ID ITEM");

        jLabel4.setText("TABELA:");

        jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, listLog, tbLog);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${acaolog}"));
        columnBinding.setColumnName("Acaolog");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${datalogo}"));
        columnBinding.setColumnName("Datalogo");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${horalog}"));
        columnBinding.setColumnName("Horalog");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${iditemlog}"));
        columnBinding.setColumnName("Iditemlog");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${idlog}"));
        columnBinding.setColumnName("Idlog");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${itemnomelog}"));
        columnBinding.setColumnName("Itemnomelog");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${tablog}"));
        columnBinding.setColumnName("Tablog");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${usuerlog}"));
        columnBinding.setColumnName("Usuerlog");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        masterScrollPane1.setViewportView(tbLog);

        jLabel6.setText("ITEM_");

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        btnSalvarLog.setText("SalvarLog");
        btnSalvarLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarLogActionPerformed(evt);
            }
        });
        jPanel3.add(btnSalvarLog);

        btnCancelaLog.setText("RefreshLog");
        btnCancelaLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelaLogActionPerformed(evt);
            }
        });
        jPanel3.add(btnCancelaLog);

        btnNovoLog.setText("NovoLog");
        btnNovoLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoLogActionPerformed(evt);
            }
        });
        jPanel3.add(btnNovoLog);

        jLabel3.setText("HORA:");

        txtTabela.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tbLog, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.tablog}"), txtTabela, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout jpFormLogLayout = new javax.swing.GroupLayout(jpFormLog);
        jpFormLog.setLayout(jpFormLogLayout);
        jpFormLogLayout.setHorizontalGroup(
            jpFormLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFormLogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpFormLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpFormLogLayout.createSequentialGroup()
                        .addGroup(jpFormLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addGroup(jpFormLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpFormLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jpFormLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpFormLogLayout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(txtUsuario)
                                .addGap(72, 72, 72))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpFormLogLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jpFormLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(ITEM))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jpFormLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtItem, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpFormLogLayout.createSequentialGroup()
                                        .addGroup(jpFormLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtIdItem, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtAcao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18))))))
                    .addGroup(jpFormLogLayout.createSequentialGroup()
                        .addGroup(jpFormLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpFormLogLayout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(txtTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6))
                            .addGroup(jpFormLogLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jpFormLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(masterScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                        .addContainerGap())))
        );
        jpFormLogLayout.setVerticalGroup(
            jpFormLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFormLogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(masterScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jpFormLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpFormLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpFormLogLayout.createSequentialGroup()
                        .addGroup(jpFormLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jpFormLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(jpFormLogLayout.createSequentialGroup()
                        .addGroup(jpFormLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAcao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpFormLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ITEM)
                            .addComponent(txtIdItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpFormLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jpFormLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTabela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(txtItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpPesquisa.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Pesquisa...", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));
        jpPesquisa.setLayout(new java.awt.GridLayout(1, 0));

        txtPesq.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesqKeyReleased(evt);
            }
        });
        jpPesquisa.add(txtPesq);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jpBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jpPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jpDados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(masterScrollPane))
                .addGap(32, 32, 32)
                .addComponent(jpFormLog, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpFormLog, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpDados, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jpBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jpPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)))
                .addComponent(masterScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        bindingGroup.bind();

        setSize(new java.awt.Dimension(537, 351));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelaActionPerformed
        em.getTransaction().rollback();
        em.getTransaction().begin();
        java.util.Collection data = query.getResultList();
        for (Object entity : data) {
            em.refresh(entity);
        }
        list.clear();
        list.addAll(data);
    }//GEN-LAST:event_btnCancelaActionPerformed

    private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirActionPerformed
        acao = ("Incluir");
        com.guina.model.Tb007modelos t = new com.guina.model.Tb007modelos();
        em.persist(t);
        list.add(t);
        int row = list.size() - 1;
        tbModelo.setRowSelectionInterval(row, row);
        tbModelo.scrollRectToVisible(tbModelo.getCellRect(row, 0, true));
    }//GEN-LAST:event_btnIncluirActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
     acao = ("Excluir");
        int[] selected = tbModelo.getSelectedRows();
        List<com.guina.model.Tb007modelos> toRemove = new ArrayList<com.guina.model.Tb007modelos>(selected.length);
        for (int idx = 0; idx < selected.length; idx++) {
            com.guina.model.Tb007modelos t = list.get(tbModelo.convertRowIndexToModel(selected[idx]));
            toRemove.add(t);
            em.remove(t);
        }
        list.removeAll(toRemove);
         //Depois de deletar Salva
        btnSalvar.doClick();
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        btnNovoLog.doClick();
        Dados();//Preenche dados
        User();//Pega Usuario
        btnSalvarLog.doClick();//Salva na tabela de log
        btnCancelaLog.doClick();//Atualiza tabela de Log
        try {
            em.getTransaction().commit();
            em.getTransaction().begin();
        } catch (RollbackException rex) {
            rex.printStackTrace();
            em.getTransaction().begin();
            List<com.guina.model.Tb007modelos> merged = new ArrayList<com.guina.model.Tb007modelos>(list.size());
            for (com.guina.model.Tb007modelos t : list) {
                merged.add(em.merge(t));
            }
            list.clear();
            list.addAll(merged);
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void txtUserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserFocusGained

    private void btnSalvarLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarLogActionPerformed
        try {
            em.getTransaction().commit();
            em.getTransaction().begin();
        } catch (RollbackException rex) {
            rex.printStackTrace();
            em.getTransaction().begin();
            List<com.guina.model.Tb010logsistema> merged = new ArrayList<com.guina.model.Tb010logsistema>(listLog.size());
            for (com.guina.model.Tb010logsistema t : listLog) {
                merged.add(em.merge(t));
            }
            listLog.clear();
            listLog.addAll(merged);
        }
    }//GEN-LAST:event_btnSalvarLogActionPerformed

    private void btnCancelaLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelaLogActionPerformed
        em.getTransaction().rollback();
        em.getTransaction().begin();
        java.util.Collection data = queryLog.getResultList();
        for (Object entity : data) {
            em.refresh(entity);
        }
        listLog.clear();
        listLog.addAll(data);
    }//GEN-LAST:event_btnCancelaLogActionPerformed

    private void btnNovoLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoLogActionPerformed
        com.guina.model.Tb010logsistema t = new com.guina.model.Tb010logsistema();
        em.persist(t);
        listLog.add(t);
        int row = listLog.size() - 1;
        tbLog.setRowSelectionInterval(row, row);
        tbLog.scrollRectToVisible(tbLog.getCellRect(row, 0, true));
    }//GEN-LAST:event_btnNovoLogActionPerformed

    private void tbModeloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbModeloMouseClicked
      acao = ("Alterar");        // TODO add your handling code here:
    }//GEN-LAST:event_tbModeloMouseClicked

    private void txtPesqKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesqKeyReleased
        uteis.maiscula(evt);
        query = em.createQuery("SELECT t FROM Tb007modelos t WHERE t.nomemodelo like :nome or t.marcamodelotb006.nomemarca like :nome  ");
        query.setParameter("nome", "%" + txtPesq.getText() + "%");
        list.clear();
        list.addAll(query.getResultList());        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesqKeyReleased

    private void txtNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyReleased
     uteis.maiscula(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        frmConsMarcaTb006 frm = new frmConsMarcaTb006(new JFrame(), true);
        frm.setVisible(true);// TODO add your handling code here:
        if (frm.isConfirmado()) {
            Tb006marcas s = frm.getMarca();
            jcMarca.getModel().setSelectedItem(s);
        }         // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows Classic".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmModeloTb007.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmModeloTb007.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmModeloTb007.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmModeloTb007.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmModeloTb007 dialog = new frmModeloTb007(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ITEM;
    public javax.swing.JButton btnCancela;
    private javax.swing.JButton btnCancelaLog;
    public javax.swing.JButton btnExcluir;
    public javax.swing.JButton btnIncluir;
    private javax.swing.JButton btnNovoLog;
    public javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnSalvarLog;
    private javax.swing.JLabel datacadmodeloLabel;
    private javax.persistence.EntityManager em;
    private javax.swing.JLabel idmodeloLabel;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JComboBox<String> jcMarca;
    private javax.swing.JPanel jpBotoes;
    private javax.swing.JPanel jpDados;
    private javax.swing.JPanel jpFormLog;
    private javax.swing.JPanel jpPesquisa;
    private java.util.List<com.guina.model.Tb007modelos> list;
    private java.util.List<com.guina.model.Tb010logsistema> listLog;
    private java.util.List<com.guina.model.Tb006marcas> listMarca;
    private java.util.List<com.guina.model.Tb001user> listUser;
    private javax.swing.JLabel marcamodelotb006Label;
    private javax.swing.JScrollPane masterScrollPane;
    private javax.swing.JScrollPane masterScrollPane1;
    private javax.swing.JLabel nomemodeloLabel;
    private javax.persistence.Query query;
    private javax.persistence.Query queryLog;
    private javax.persistence.Query queryMarca;
    private javax.persistence.Query queryUser;
    private javax.swing.JTable tbLog;
    public javax.swing.JTable tbModelo;
    private javax.swing.JTextField txtAcao;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtIdItem;
    private javax.swing.JTextField txtItem;
    private javax.swing.JTextField txtNome;
    public javax.swing.JTextField txtPesq;
    private javax.swing.JTextField txtTabela;
    public javax.swing.JTextField txtUser;
    public javax.swing.JLabel txtUsuario;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
 ////////////Inicio funçao de log para o sistema///////////////////////////
    public void Dados() {
        //Dados para fazerlog
        Date data = new Date();
        SimpleDateFormat horaFormatada = new SimpleDateFormat("HH:mm:ss");
        SimpleDateFormat dataFormatada = new SimpleDateFormat("dd/MM/yyyy");
        //Pegar a hora
        txtHora.setText(String.valueOf(horaFormatada.format(data)));
        //Pegar a Data
        txtData.setText(String.valueOf(dataFormatada.format(data)));
        //Pegar tabela
        txtTabela.setText(tb);
        //Pega a ação
        txtAcao.setText(acao);
        //Pega o item
        txtIdItem.setText(txtId.getText());
        //Pega nome item
        txtItem.setText(txtNome.getText());
    }

    public void User() {
        int user = (Integer.parseInt(txtUsuario.getText()));
        queryUser = em.createQuery("SELECT t FROM Tb001user t WHERE t.iduser = :id ");
        queryUser.setParameter("id", (Integer.parseInt(txtUsuario.getText())));
        List<Tb001user> data = queryUser.getResultList();
        if (data.size() > 0) {
            String args[] = new String[1];
            args[0] = data.get(0).getNomeuser();
            txtUser.setText(args[0]);
        }
    }
    ////////////Fim funçao de log para o sistema///////////////////////////
}
