/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.guina.view;

import com.guina.model.Tb015ocorrencias;
import com.guina.consulta.frmConsLojaTb011;
import com.guina.model.Tb001user;
import com.guina.model.Tb011lojas;
import com.guina.model.Tb014nboletas;
import com.guina.uteis.uteis;
import java.beans.Beans;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.RollbackException;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Agnaldo
 */
public class frmOcorrenciaTb015 extends javax.swing.JDialog {

    //////nome da tabela////////
    String tb = "tb014lojas";
    String acao, aux;// aux variavel da funcao Id
    int n, novo; // variavel da funcao Id
    /////////////////////////

    public frmOcorrenciaTb015(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        if (!Beans.isDesignTime()) {
            em.getTransaction().begin();
        }

        //COLOCAR BARRA HORIZONTAL - TABELA ITENS
        tbOcorrencia.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        //ORGANIZAR TABELA MODO CRESCENTE OU DECRESCENTE - TABELA DE ITENS
        TableModel modelo = (TableModel) tbOcorrencia.getModel();
        tbOcorrencia.setRowSorter(new TableRowSorter(modelo));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        em = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("permissaoPU").createEntityManager();
        query = java.beans.Beans.isDesignTime() ? null : em.createQuery("SELECT t FROM Tb015ocorrencias t");
        list = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(query.getResultList());
        queryLoja = java.beans.Beans.isDesignTime() ? null : em.createQuery("SELECT t FROM Tb011lojas t");
        listLoja = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(queryLoja.getResultList());
        queryUser = java.beans.Beans.isDesignTime() ? null : em.createQuery("SELECT t FROM Tb001user t");
        listUser = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(queryUser.getResultList());
        queryLog = java.beans.Beans.isDesignTime() ? null : em.createQuery("SELECT t FROM Tb010logsistema t");
        listLog = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(queryLog.getResultList());
        jpLog = new javax.swing.JPanel();
        txtIdItem = new javax.swing.JTextField();
        txtItem = new javax.swing.JTextField();
        txtUser = new javax.swing.JTextField();
        txtData = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtHora = new javax.swing.JTextField();
        txtAcao = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ITEM = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        masterScrollPane1 = new javax.swing.JScrollPane();
        tbLog = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnSalvarLog = new javax.swing.JButton();
        btnCancelaLog = new javax.swing.JButton();
        btnNovoLog = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtTabela = new javax.swing.JTextField();
        masterScrollPane = new javax.swing.JScrollPane();
        tbOcorrencia = new javax.swing.JTable();
        jpDados = new javax.swing.JPanel();
        txtLancSistema = new javax.swing.JTextField();
        idocorrenciaLabel = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        dataocLabel = new javax.swing.JLabel();
        txtDiferenca = new javax.swing.JTextField();
        diferencavlrocLabel = new javax.swing.JLabel();
        valortabmanualocLabel = new javax.swing.JLabel();
        valorsistemaocLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObs = new javax.swing.JTextArea();
        lojaacLabel = new javax.swing.JLabel();
        txtLancManual = new javax.swing.JTextField();
        jdData = new com.toedter.calendar.JDateChooser();
        jcLoja = new javax.swing.JComboBox<>();
        btnPesqLoja = new javax.swing.JButton();
        jpBotoes = new javax.swing.JPanel();
        btnIncluir = new javax.swing.JButton();
        btnCancela = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        txtPesq = new javax.swing.JTextField();
        jData = new com.toedter.calendar.JDateChooser();
        btnLimpa = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Ocorrencia");

        jpLog.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Log"));

        txtIdItem.setEditable(false);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tbLog, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.iditemlog}"), txtIdItem, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        txtItem.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tbLog, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.itemnomelog}"), txtItem, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        txtUser.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tbLog, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.usuerlog}"), txtUser, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        txtUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUserFocusGained(evt);
            }
        });

        txtData.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tbLog, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.datalogo}"), txtData, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        txtUsuario.setText("USUARIO");

        jLabel1.setText("USER:");

        jLabel5.setText("AÇÃO");

        txtHora.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tbLog, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.horalog}"), txtHora, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        txtAcao.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tbLog, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.acaolog}"), txtAcao, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jLabel2.setText("DATA:");

        ITEM.setText("ID ITEM");

        jLabel4.setText("TABELA:");

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, listLog, tbLog);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${acaolog}"));
        columnBinding.setColumnName("Acaolog");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${datalogo}"));
        columnBinding.setColumnName("Datalogo");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${horalog}"));
        columnBinding.setColumnName("Horalog");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${iditemlog}"));
        columnBinding.setColumnName("Iditemlog");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${idlog}"));
        columnBinding.setColumnName("Idlog");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${itemnomelog}"));
        columnBinding.setColumnName("Itemnomelog");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${tablog}"));
        columnBinding.setColumnName("Tablog");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${usuerlog}"));
        columnBinding.setColumnName("Usuerlog");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        masterScrollPane1.setViewportView(tbLog);

        jLabel6.setText("ITEM_");

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        btnSalvarLog.setText("SalvarLog");
        btnSalvarLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarLogActionPerformed(evt);
            }
        });
        jPanel3.add(btnSalvarLog);

        btnCancelaLog.setText("RefreshLog");
        btnCancelaLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelaLogActionPerformed(evt);
            }
        });
        jPanel3.add(btnCancelaLog);

        btnNovoLog.setText("NovoLog");
        btnNovoLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoLogActionPerformed(evt);
            }
        });
        jPanel3.add(btnNovoLog);

        jLabel3.setText("HORA:");

        txtTabela.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tbLog, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.tablog}"), txtTabela, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout jpLogLayout = new javax.swing.GroupLayout(jpLog);
        jpLog.setLayout(jpLogLayout);
        jpLogLayout.setHorizontalGroup(
            jpLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpLogLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpLogLayout.createSequentialGroup()
                            .addGap(51, 51, 51)
                            .addComponent(txtTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtItem))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpLogLayout.createSequentialGroup()
                            .addGroup(jpLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addGroup(jpLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jpLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jpLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jpLogLayout.createSequentialGroup()
                                    .addComponent(ITEM)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtIdItem))
                                .addComponent(txtUsuario)
                                .addGroup(jpLogLayout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtAcao, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(masterScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpLogLayout.setVerticalGroup(
            jpLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(masterScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jpLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpLogLayout.createSequentialGroup()
                        .addGroup(jpLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpLogLayout.createSequentialGroup()
                        .addGroup(jpLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtAcao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jpLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(ITEM)
                    .addComponent(txtIdItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jpLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTabela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(txtItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, list, tbOcorrencia);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${idocorrencia}"));
        columnBinding.setColumnName("ID");
        columnBinding.setColumnClass(Long.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${dataoc}"));
        columnBinding.setColumnName("Data");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${lojaac}"));
        columnBinding.setColumnName("Loja");
        columnBinding.setColumnClass(com.guina.model.Tb011lojas.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${valorsistemaoc}"));
        columnBinding.setColumnName("Valor Sistema");
        columnBinding.setColumnClass(Float.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${valortabmanualoc}"));
        columnBinding.setColumnName("Valor Manual");
        columnBinding.setColumnClass(Float.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${diferencavlroc}"));
        columnBinding.setColumnName("Diferenca");
        columnBinding.setColumnClass(Float.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${obsoc}"));
        columnBinding.setColumnName("Obs");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        tbOcorrencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbOcorrenciaMouseClicked(evt);
            }
        });
        masterScrollPane.setViewportView(tbOcorrencia);
        if (tbOcorrencia.getColumnModel().getColumnCount() > 0) {
            tbOcorrencia.getColumnModel().getColumn(0).setMinWidth(2);
            tbOcorrencia.getColumnModel().getColumn(0).setMaxWidth(2);
            tbOcorrencia.getColumnModel().getColumn(1).setMinWidth(70);
            tbOcorrencia.getColumnModel().getColumn(1).setMaxWidth(80);
            tbOcorrencia.getColumnModel().getColumn(2).setMinWidth(150);
            tbOcorrencia.getColumnModel().getColumn(2).setMaxWidth(200);
            tbOcorrencia.getColumnModel().getColumn(3).setMinWidth(150);
            tbOcorrencia.getColumnModel().getColumn(3).setMaxWidth(150);
            tbOcorrencia.getColumnModel().getColumn(4).setMinWidth(150);
            tbOcorrencia.getColumnModel().getColumn(4).setMaxWidth(150);
            tbOcorrencia.getColumnModel().getColumn(5).setMinWidth(150);
            tbOcorrencia.getColumnModel().getColumn(5).setMaxWidth(150);
            tbOcorrencia.getColumnModel().getColumn(6).setMinWidth(200);
            tbOcorrencia.getColumnModel().getColumn(6).setMaxWidth(250);
        }

        jpDados.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tbOcorrencia, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.valorsistemaoc}"), txtLancSistema, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tbOcorrencia, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), txtLancSistema, org.jdesktop.beansbinding.BeanProperty.create("editable"));
        bindingGroup.addBinding(binding);

        txtLancSistema.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtLancSistemaFocusLost(evt);
            }
        });

        idocorrenciaLabel.setText("ID:");

        txtId.setEditable(false);
        txtId.setBackground(new java.awt.Color(153, 204, 255));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tbOcorrencia, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.idocorrencia}"), txtId, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tbOcorrencia, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), txtId, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        dataocLabel.setText("Data:");

        txtDiferenca.setEditable(false);
        txtDiferenca.setBackground(new java.awt.Color(255, 255, 204));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tbOcorrencia, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.diferencavlroc}"), txtDiferenca, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tbOcorrencia, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), txtDiferenca, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        txtDiferenca.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDiferencaFocusGained(evt);
            }
        });

        diferencavlrocLabel.setText("Dierença R$");

        valortabmanualocLabel.setText("Lanc.Manual : R$");

        valorsistemaocLabel.setText("Lanc Sistema: R$");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Observação", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        txtObs.setColumns(20);
        txtObs.setRows(5);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tbOcorrencia, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.obsoc}"), txtObs, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tbOcorrencia, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), txtObs, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        jScrollPane1.setViewportView(txtObs);

        jPanel1.add(jScrollPane1);

        lojaacLabel.setText("Loja:");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tbOcorrencia, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.valortabmanualoc}"), txtLancManual, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tbOcorrencia, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), txtLancManual, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        txtLancManual.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtLancManualFocusLost(evt);
            }
        });

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tbOcorrencia, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.dataoc}"), jdData, org.jdesktop.beansbinding.BeanProperty.create("date"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tbOcorrencia, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), jdData, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, listLoja, jcLoja);
        bindingGroup.addBinding(jComboBoxBinding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tbOcorrencia, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.lojaac}"), jcLoja, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tbOcorrencia, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), jcLoja, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        btnPesqLoja.setText("jButton2");
        btnPesqLoja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesqLojaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpDadosLayout = new javax.swing.GroupLayout(jpDados);
        jpDados.setLayout(jpDadosLayout);
        jpDadosLayout.setHorizontalGroup(
            jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(valortabmanualocLabel)
                    .addComponent(idocorrenciaLabel))
                .addGap(13, 13, 13)
                .addGroup(jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpDadosLayout.createSequentialGroup()
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dataocLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jdData, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lojaacLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcLoja, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jpDadosLayout.createSequentialGroup()
                        .addComponent(txtLancManual, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(valorsistemaocLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLancSistema, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(diferencavlrocLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDiferenca, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPesqLoja, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpDadosLayout.setVerticalGroup(
            jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDadosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idocorrenciaLabel)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(dataocLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jdData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lojaacLabel)
                        .addComponent(jcLoja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPesqLoja)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valortabmanualocLabel)
                    .addComponent(txtLancManual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valorsistemaocLabel)
                    .addComponent(txtLancSistema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(diferencavlrocLabel)
                    .addComponent(txtDiferenca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpBotoes.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jpBotoes.setLayout(new java.awt.GridLayout(1, 0));

        btnIncluir.setText("Novo");
        btnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirActionPerformed(evt);
            }
        });
        jpBotoes.add(btnIncluir);

        btnCancela.setText("Cancela");
        btnCancela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelaActionPerformed(evt);
            }
        });
        jpBotoes.add(btnCancela);

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        jpBotoes.add(btnSalvar);

        btnExcluir.setText("Delete");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        jpBotoes.add(btnExcluir);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Pesquisa...", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));
        jPanel4.setLayout(new java.awt.GridLayout());

        txtPesq.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPesqFocusLost(evt);
            }
        });
        txtPesq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesqActionPerformed(evt);
            }
        });
        txtPesq.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesqKeyReleased(evt);
            }
        });
        jPanel4.add(txtPesq);
        jPanel4.add(jData);

        btnLimpa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/guina/icone/borracha.png"))); // NOI18N
        btnLimpa.setToolTipText("Limpa Consulta");
        btnLimpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpaActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/guina/icone/pesq.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(masterScrollPane)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jpDados, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jpBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnLimpa, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jpLog, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpLog, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLimpa)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jpBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(masterScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnLimpa, jButton1});

        bindingGroup.bind();

        setSize(new java.awt.Dimension(681, 424));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirActionPerformed
        txtObs.setText("OK");
        //recebe  a ação incluir
        MaxId();//função verifica o ultimo id
        acao = ("Incluir");

        com.guina.model.Tb015ocorrencias t = new com.guina.model.Tb015ocorrencias();
        em.persist(t);
        list.add(t);
        int row = list.size() - 1;
        tbOcorrencia.setRowSelectionInterval(row, row);
        tbOcorrencia.scrollRectToVisible(tbOcorrencia.getCellRect(row, 0, true));

        txtId.setText(Integer.toString(novo));
    }//GEN-LAST:event_btnIncluirActionPerformed

    private void btnCancelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelaActionPerformed
        em.getTransaction().rollback();
        em.getTransaction().begin();
        java.util.Collection data = query.getResultList();
        for (Object entity : data) {
            em.refresh(entity);
        }
        list.clear();
        list.addAll(data);


    }//GEN-LAST:event_btnCancelaActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        //inicia função de Log
        btnNovoLog.doClick();//incia o log
        Dados();//Preenche dados
        User();//Pega Usuario
        btnSalvarLog.doClick();//Salva na tabela de log
        btnCancelaLog.doClick();//Atualiza tabela de Log

        try {
            em.getTransaction().commit();
            em.getTransaction().begin();
        } catch (RollbackException rex) {
            rex.printStackTrace();
            em.getTransaction().begin();
            List<com.guina.model.Tb015ocorrencias> merged = new ArrayList<com.guina.model.Tb015ocorrencias>(list.size());
            for (com.guina.model.Tb015ocorrencias t : list) {
                merged.add(em.merge(t));
            }
            list.clear();
            list.addAll(merged);
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed

        acao = ("Excluir");
        int[] selected = tbOcorrencia.getSelectedRows();
        List<com.guina.model.Tb015ocorrencias> toRemove = new ArrayList<com.guina.model.Tb015ocorrencias>(selected.length);
        for (int idx = 0; idx < selected.length; idx++) {
            com.guina.model.Tb015ocorrencias t = list.get(tbOcorrencia.convertRowIndexToModel(selected[idx]));
            toRemove.add(t);
            em.remove(t);
        }
        list.removeAll(toRemove);
        btnSalvar.doClick();
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void txtUserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserFocusGained

    private void btnSalvarLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarLogActionPerformed
        try {
            em.getTransaction().commit();
            em.getTransaction().begin();
        } catch (RollbackException rex) {
            rex.printStackTrace();
            em.getTransaction().begin();
            List<com.guina.model.Tb010logsistema> merged = new ArrayList<com.guina.model.Tb010logsistema>(listLog.size());
            for (com.guina.model.Tb010logsistema t : listLog) {
                merged.add(em.merge(t));
            }
            listLog.clear();
            listLog.addAll(merged);
        }
    }//GEN-LAST:event_btnSalvarLogActionPerformed

    private void btnCancelaLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelaLogActionPerformed
        em.getTransaction().rollback();
        em.getTransaction().begin();
        java.util.Collection data = queryLog.getResultList();
        for (Object entity : data) {
            em.refresh(entity);
        }
        listLog.clear();
        listLog.addAll(data);
    }//GEN-LAST:event_btnCancelaLogActionPerformed

    private void btnNovoLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoLogActionPerformed
        com.guina.model.Tb010logsistema t = new com.guina.model.Tb010logsistema();
        em.persist(t);
        listLog.add(t);
        int row = listLog.size() - 1;
        tbLog.setRowSelectionInterval(row, row);
        tbLog.scrollRectToVisible(tbLog.getCellRect(row, 0, true));
    }//GEN-LAST:event_btnNovoLogActionPerformed

    private void txtLancManualFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLancManualFocusLost
        String real = txtLancManual.getText();
        String valor = real.replace(",", ".");
        txtLancManual.setText(valor);         // TODO add your handling code here:
    }//GEN-LAST:event_txtLancManualFocusLost

    private void txtLancSistemaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLancSistemaFocusLost
        String real1 = txtLancSistema.getText();
        String valor1 = real1.replace(",", ".");
        txtLancSistema.setText(valor1);        // TODO add your handling code here:
    }//GEN-LAST:event_txtLancSistemaFocusLost

    private void txtDiferencaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDiferencaFocusGained
        float a = Float.parseFloat(txtLancSistema.getText());
        float b = Float.parseFloat(txtLancManual.getText());
        float c = (a - b);
        txtDiferenca.setText(String.valueOf(c));

        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiferencaFocusGained

    private void txtPesqFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPesqFocusLost
        //      btnLimpa.doClick();        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesqFocusLost

    private void txtPesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesqActionPerformed

    private void txtPesqKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesqKeyReleased
        uteis.maiscula(evt);
        query = em.createQuery("SELECT t FROM Tb015ocorrencias t WHERE t.lojaac.descLoja LIKE :nome");
        query.setParameter("nome", "%" + txtPesq.getText() + "%");
        list.clear();
        list.addAll(query.getResultList());  // TODO add your handling code here:
    }//GEN-LAST:event_txtPesqKeyReleased

    private void btnLimpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpaActionPerformed
        txtPesq.setText("");
        jData.setDate(null);
        query = em.createQuery("SELECT t FROM Tb015ocorrencias t ");
        list.clear();
        list.addAll(query.getResultList());
        txtPesq.requestFocus();// TODO add your handling code here:
    }//GEN-LAST:event_btnLimpaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        query = em.createQuery("SELECT t FROM Tb015ocorrencias t WHERE t.dataoc BETWEEN :jdata and :jdata AND t.lojaac.descLoja LIKE :nome");
        query.setParameter("nome", "%" + txtPesq.getText() + "%");
        query.setParameter("jdata", jData.getDate());
        list.clear();
        list.addAll(query.getResultList());          // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnPesqLojaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesqLojaActionPerformed
        frmConsLojaTb011 frm = new frmConsLojaTb011(new JFrame(), true);
        frm.setVisible(true);// TODO add your handling code here:
        if (frm.isConfirmado()) {
            Tb011lojas l = frm.getLoja();
            jcLoja.getModel().setSelectedItem(l);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnPesqLojaActionPerformed

    private void tbOcorrenciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbOcorrenciaMouseClicked
    acao = "Alterar";        // TODO add your handling code here:
    }//GEN-LAST:event_tbOcorrenciaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows Classic".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmOcorrenciaTb015.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmOcorrenciaTb015.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmOcorrenciaTb015.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmOcorrenciaTb015.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmOcorrenciaTb015 dialog = new frmOcorrenciaTb015(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ITEM;
    public javax.swing.JButton btnCancela;
    private javax.swing.JButton btnCancelaLog;
    public javax.swing.JButton btnExcluir;
    public javax.swing.JButton btnIncluir;
    private javax.swing.JButton btnLimpa;
    private javax.swing.JButton btnNovoLog;
    private javax.swing.JButton btnPesqLoja;
    public javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnSalvarLog;
    private javax.swing.JLabel dataocLabel;
    private javax.swing.JLabel diferencavlrocLabel;
    private javax.persistence.EntityManager em;
    private javax.swing.JLabel idocorrenciaLabel;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcLoja;
    private com.toedter.calendar.JDateChooser jdData;
    private javax.swing.JPanel jpBotoes;
    private javax.swing.JPanel jpDados;
    private javax.swing.JPanel jpLog;
    private java.util.List<com.guina.model.Tb015ocorrencias> list;
    private java.util.List<com.guina.model.Tb010logsistema> listLog;
    private java.util.List<com.guina.model.Tb011lojas> listLoja;
    private java.util.List<com.guina.model.Tb001user> listUser;
    private javax.swing.JLabel lojaacLabel;
    private javax.swing.JScrollPane masterScrollPane;
    private javax.swing.JScrollPane masterScrollPane1;
    private javax.persistence.Query query;
    private javax.persistence.Query queryLog;
    private javax.persistence.Query queryLoja;
    private javax.persistence.Query queryUser;
    public javax.swing.JTable tbLog;
    public javax.swing.JTable tbOcorrencia;
    private javax.swing.JTextField txtAcao;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtDiferenca;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtIdItem;
    private javax.swing.JTextField txtItem;
    private javax.swing.JTextField txtLancManual;
    private javax.swing.JTextField txtLancSistema;
    public javax.swing.JTextArea txtObs;
    public javax.swing.JTextField txtPesq;
    private javax.swing.JTextField txtTabela;
    public javax.swing.JTextField txtUser;
    public javax.swing.JLabel txtUsuario;
    private javax.swing.JLabel valorsistemaocLabel;
    private javax.swing.JLabel valortabmanualocLabel;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
///////////////FUNÇOES DO SISTEMA/////////////////////////////////
    //funçaõ pega o ultimo id e gera id para cadastro
    public void MaxId() {
        query = em.createQuery("SELECT t FROM Tb015ocorrencias t ORDER BY t.idocorrencia DESC");
        List<Tb015ocorrencias> ocorr = query.getResultList();
        if (ocorr.size() == 0) {
            txtId.setText("1");
            novo = (Integer.parseInt(txtId.getText()));
        } else if (ocorr.size() > 0) {
            String args[] = new String[1];
            args[0] = ocorr.get(0).getIdocorrencia().toString();
            n = (Integer.parseInt(args[0]));
            txtId.setText(Integer.toString(n));//Recupera o ultimo codigo
            novo = (Integer.parseInt(txtId.getText()) + 1);
        }
    }

    public void Dados() {
        //Dados para fazerlog
        Date data = new Date();
        SimpleDateFormat horaFormatada = new SimpleDateFormat("HH:mm:ss");
        SimpleDateFormat dataFormatada = new SimpleDateFormat("dd/MM/yyyy");
        //Pegar a hora
        txtHora.setText(String.valueOf(horaFormatada.format(data)));
        //Pegar a Data
        txtData.setText(String.valueOf(dataFormatada.format(data)));
        //Pegar tabela
        txtTabela.setText(tb);
        //Pega a ação
        txtAcao.setText(acao);
        //Pega o item
        txtIdItem.setText(txtId.getText());
        //Pega nome item
        txtItem.setText(jcLoja.getSelectedItem().toString());
    }

    public void User() {
        int user = (Integer.parseInt(txtUsuario.getText()));
        queryUser = em.createQuery("SELECT t FROM Tb001user t WHERE t.iduser = :id ");
        queryUser.setParameter("id", (Integer.parseInt(txtUsuario.getText())));
        List<Tb001user> data = queryUser.getResultList();
        if (data.size() > 0) {
            String args[] = new String[1];
            args[0] = data.get(0).getNomeuser();
            txtUser.setText(args[0]);
        }
    }
}
