/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.guina.view;

import com.guina.model.Tb002acesso;
import java.beans.Beans;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Agnaldo
 */
public class frmPrincipal extends javax.swing.JFrame {

    //Telas para permissao
    frmFornecedorTb008 fornecedor = new frmFornecedorTb008(this, true);
    frmAcessoTb002 acesso = new frmAcessoTb002(this, true);
    frmUserTb001 usuario = new frmUserTb001(this, true);
    frmLogadoTb009 logado = new frmLogadoTb009(this, true);
    frmLogTb010 log = new frmLogTb010(this, true);
    frmMarcaTb006 marca = new frmMarcaTb006(this, true);
    frmUnidadeTb005 un = new frmUnidadeTb005(this, true);
    frmCategoriaTb004 cat = new frmCategoriaTb004(this, true);
    frmModeloTb007 mod = new frmModeloTb007(this, true);
    frmProdutoTb003 prod = new frmProdutoTb003(this, true);
    frmTabelaTb000 tab = new frmTabelaTb000(this, true);
    frmLojasTb011 loja = new frmLojasTb011(this, true);
    frmVendaTb012 venda = new frmVendaTb012(this,true);
    frmVendedorasTb013 vend = new frmVendedorasTb013(this,true);
    frmBoletaTb014 boleto = new frmBoletaTb014(this,true);
    frmOcorrenciaTb015 ocorrencia = new frmOcorrenciaTb015(this,true);
    FrmFichaConsT019 ficha = new FrmFichaConsT019(this, true);
    FrmCliLojas020 cliente = new FrmCliLojas020(this,true);
    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
        if (!Beans.isDesignTime()) {
            em.getTransaction().begin();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        em = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("permissaoPU").createEntityManager();
        query = java.beans.Beans.isDesignTime() ? null : em.createQuery("SELECT t FROM Tb002acesso t");
        list = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(query.getResultList());
        queryLogado = java.beans.Beans.isDesignTime() ? null : em.createQuery("SELECT t FROM Tb009logados t");
        listLogado = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(queryLogado.getResultList());
        jpSeparador = new javax.swing.JPanel();
        jpMenu = new javax.swing.JPanel();
        btnFornecedor = new javax.swing.JButton();
        btnUsuario = new javax.swing.JButton();
        btnAcesso = new javax.swing.JButton();
        btnLogof = new javax.swing.JButton();
        txtUser = new javax.swing.JLabel();
        txtInserir = new javax.swing.JLabel();
        txtEditar = new javax.swing.JLabel();
        txtExcluir = new javax.swing.JLabel();
        txtPesquisa = new javax.swing.JLabel();
        jpanelInferior = new java.awt.Panel();
        txtUsuario = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jpConserto = new javax.swing.JPanel();
        btnFicha = new javax.swing.JButton();
        btnCli = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        menuLog = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jmVendas = new javax.swing.JMenu();
        menuLoja = new javax.swing.JMenuItem();
        menuVenda = new javax.swing.JMenuItem();
        menuVendedor = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmOcorrencia = new javax.swing.JMenuItem();
        menuConserto = new javax.swing.JMenu();
        menuCadFichaConserto = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();

        jpSeparador.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jpSeparadorLayout = new javax.swing.GroupLayout(jpSeparador);
        jpSeparador.setLayout(jpSeparadorLayout);
        jpSeparadorLayout.setHorizontalGroup(
            jpSeparadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpSeparadorLayout.setVerticalGroup(
            jpSeparadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("SISTPERMISSAO");
        setExtendedState(6);

        jpMenu.setBackground(new java.awt.Color(153, 204, 255));
        jpMenu.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro Geral", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));
        jpMenu.setLayout(new java.awt.GridLayout(1, 0));

        btnFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/guina/icone/empresa.png"))); // NOI18N
        btnFornecedor.setText("Fornecedor");
        btnFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFornecedorActionPerformed(evt);
            }
        });
        jpMenu.add(btnFornecedor);

        btnUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/guina/icone/cliente.png"))); // NOI18N
        btnUsuario.setText("Usuarios");
        btnUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarioActionPerformed(evt);
            }
        });
        jpMenu.add(btnUsuario);

        btnAcesso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/guina/icone/acesso.png"))); // NOI18N
        btnAcesso.setText("Acesso Usuarios");
        btnAcesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcessoActionPerformed(evt);
            }
        });
        jpMenu.add(btnAcesso);

        btnLogof.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/guina/icone/logof.png"))); // NOI18N
        btnLogof.setText("Trocar Usuario");
        btnLogof.setToolTipText("Fazer Logof");
        btnLogof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogofActionPerformed(evt);
            }
        });
        jpMenu.add(btnLogof);

        txtUser.setForeground(new java.awt.Color(204, 204, 204));
        txtUser.setText("jLabel1");
        txtUser.setEnabled(false);

        txtInserir.setForeground(new java.awt.Color(204, 204, 204));
        txtInserir.setText("Inserir");
        txtInserir.setEnabled(false);

        txtEditar.setForeground(new java.awt.Color(204, 204, 204));
        txtEditar.setText("Editar");
        txtEditar.setEnabled(false);

        txtExcluir.setForeground(new java.awt.Color(204, 204, 204));
        txtExcluir.setText("Excluir");
        txtExcluir.setEnabled(false);

        txtPesquisa.setForeground(new java.awt.Color(204, 204, 204));
        txtPesquisa.setText("Pesquisa");
        txtPesquisa.setEnabled(false);

        jpanelInferior.setBackground(new java.awt.Color(102, 153, 255));
        jpanelInferior.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N

        txtUsuario.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        txtUsuario.setText("Usuario: Suporte");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel2.setText("© Copyright 2001-2017 Copyright - Direitos Reservados- ADM  ");
        jLabel2.setToolTipText("");

        javax.swing.GroupLayout jpanelInferiorLayout = new javax.swing.GroupLayout(jpanelInferior);
        jpanelInferior.setLayout(jpanelInferiorLayout);
        jpanelInferiorLayout.setHorizontalGroup(
            jpanelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelInferiorLayout.createSequentialGroup()
                .addComponent(txtUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );
        jpanelInferiorLayout.setVerticalGroup(
            jpanelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelInferiorLayout.createSequentialGroup()
                .addGap(0, 9, Short.MAX_VALUE)
                .addGroup(jpanelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsuario)
                    .addComponent(jLabel2)))
        );

        jpConserto.setBackground(new java.awt.Color(153, 204, 255));
        jpConserto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro Conserto", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));
        jpConserto.setLayout(new java.awt.GridLayout());

        btnFicha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/guina/icone/ficha.png"))); // NOI18N
        btnFicha.setText("Ficha");
        btnFicha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFichaActionPerformed(evt);
            }
        });
        jpConserto.add(btnFicha);

        btnCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/guina/icone/cli.png"))); // NOI18N
        btnCli.setText("Cliente");
        btnCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCliActionPerformed(evt);
            }
        });
        jpConserto.add(btnCli);

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/guina/icone/sair.jpeg"))); // NOI18N
        btnSair.setToolTipText("Sair Sistema");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        jpConserto.add(btnSair);

        jMenu1.setText("Cadastros");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/guina/icone/empresa.png"))); // NOI18N
        jMenuItem1.setText("Fornecedores");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/guina/icone/reg.png"))); // NOI18N
        jMenuItem3.setText("Marcas");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/guina/icone/unidade.png"))); // NOI18N
        jMenuItem6.setText("Unidades");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/guina/icone/cat.png"))); // NOI18N
        jMenuItem7.setText("Categoria");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/guina/icone/perifericos.png"))); // NOI18N
        jMenuItem8.setText("Modelo");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem8);

        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/guina/icone/produto.jpg"))); // NOI18N
        jMenuItem9.setText("Produto");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem9);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Relatorios");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("T.I");

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/guina/icone/cliente.png"))); // NOI18N
        jMenuItem4.setText("Usuarios");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/guina/icone/acesso.png"))); // NOI18N
        jMenuItem5.setText("Controle de Acessos");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/guina/icone/logado.png"))); // NOI18N
        jMenuItem2.setText("Logado SIS");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        menuLog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/guina/icone/log.png"))); // NOI18N
        menuLog.setText("Log Sistema");
        menuLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLogActionPerformed(evt);
            }
        });
        jMenu3.add(menuLog);

        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/guina/icone/tabelas.png"))); // NOI18N
        jMenuItem10.setText("Tabelas Sistema");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem10);

        jMenuBar1.add(jMenu3);

        jmVendas.setText("Vendas");

        menuLoja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/guina/icone/loja.png"))); // NOI18N
        menuLoja.setText("Cad Lojas");
        menuLoja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLojaActionPerformed(evt);
            }
        });
        jmVendas.add(menuLoja);

        menuVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/guina/icone/venda.png"))); // NOI18N
        menuVenda.setText("Vendas");
        menuVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVendaActionPerformed(evt);
            }
        });
        jmVendas.add(menuVenda);

        menuVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/guina/icone/vendedor.png"))); // NOI18N
        menuVendedor.setText("Vendedor");
        menuVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVendedorActionPerformed(evt);
            }
        });
        jmVendas.add(menuVendedor);

        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/guina/icone/boleta.png"))); // NOI18N
        jMenuItem11.setText("Boleta");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jmVendas.add(jMenuItem11);
        jmVendas.add(jSeparator1);

        jmOcorrencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/guina/icone/ocorre.png"))); // NOI18N
        jmOcorrencia.setText("Ocorrencia");
        jmOcorrencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmOcorrenciaActionPerformed(evt);
            }
        });
        jmVendas.add(jmOcorrencia);

        jMenuBar1.add(jmVendas);

        menuConserto.setText("Conserto");

        menuCadFichaConserto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/guina/icone/ficha.png"))); // NOI18N
        menuCadFichaConserto.setText("Cad Ficha Conserto");
        menuCadFichaConserto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadFichaConsertoActionPerformed(evt);
            }
        });
        menuConserto.add(menuCadFichaConserto);

        jMenuItem13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/guina/icone/cli.png"))); // NOI18N
        jMenuItem13.setText("Cad Cliente Loja");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        menuConserto.add(jMenuItem13);
        menuConserto.add(jSeparator2);

        jMenuItem14.setText("Consulta Ficha Conserto");
        menuConserto.add(jMenuItem14);

        jMenuItem15.setText("Consulta Cliente");
        menuConserto.add(jMenuItem15);

        jMenuItem16.setText("Consulta Produto Loja");
        menuConserto.add(jMenuItem16);

        jMenuBar1.add(menuConserto);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanelInferior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtUser)
                .addGap(18, 18, 18)
                .addComponent(txtInserir)
                .addGap(18, 18, 18)
                .addComponent(txtEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPesquisa)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpConserto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(301, 301, 301))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpConserto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 359, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUser)
                    .addComponent(txtInserir)
                    .addComponent(txtEditar)
                    .addComponent(txtExcluir)
                    .addComponent(txtPesquisa))
                .addGap(2, 2, 2)
                .addComponent(jpanelInferior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setSize(new java.awt.Dimension(969, 538));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFornecedorActionPerformed
        int user = (Integer.parseInt(txtUser.getText()));
        query = em.createQuery("SELECT t FROM Tb002acesso t WHERE t.iduser.iduser = :id and t.tbacessotb000.idtabela = 9 ");
        query.setParameter("id", (Integer.parseInt(txtUser.getText())));
        List<Tb002acesso> data = query.getResultList();
        if (data.size() > 0) {
            String args[] = new String[4];
            args[0] = data.get(0).getInseriracesso().toString();
            args[1] = data.get(0).getEditaracesso().toString();
            args[2] = data.get(0).getExcluiracesso().toString();
            args[3] = data.get(0).getConsultaracesso().toString();

            txtInserir.setText(args[0]);
            txtEditar.setText(args[1]);
            txtExcluir.setText(args[2]);
            txtPesquisa.setText(args[3]);

            //Botao Inserir//////////////////////////////////////
            if (txtInserir.getText().equals("true")) {
                fornecedor.btnInserir.setEnabled(true);
                //  fornecedor.txtMsg.setText("Com Permissao");
            } else {
                fornecedor.btnInserir.setEnabled(false);
                //    fornecedor.txtMsg.setText("Sem Permissao ");
            }
            //  Botao Excluir/////////////////////////////////////////
            if (txtExcluir.getText().equals("true")) {
                fornecedor.btnExcluir.setEnabled(true);
            } else {
                fornecedor.btnExcluir.setEnabled(false);
            }
            //Botao Salvar - Planilhas/////////////////////////////////
            if (txtPesquisa.getText().equals("true")) {
                fornecedor.btnSalvar.setEnabled(true);
                fornecedor.txtPesq.setEnabled(true);
                fornecedor.tbForn.setEnabled(true);
            } else {
                fornecedor.btnSalvar.setEnabled(false);
                fornecedor.txtPesq.setEnabled(false);
                fornecedor.tbForn.setEnabled(false);
            }
            //  Botao Editar/////////////////////////////////////////
            if (txtEditar.getText().equals("true")) {
                fornecedor.txtPesq.setEnabled(true);
            } else {
                fornecedor.btnExcluir.setEnabled(false);
            }
            fornecedor.txtUsuario.setText(txtUser.getText());
            fornecedor.setVisible(true);

        } else {
            JOptionPane.showMessageDialog(null, "Sem acesso ao modulo!!");

        }


    }//GEN-LAST:event_btnFornecedorActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        btnFornecedor.doClick();        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        btnUsuario.doClick();        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        btnAcesso.doClick();         // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void btnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioActionPerformed
        int user = (Integer.parseInt(txtUser.getText()));
        query = em.createQuery("SELECT t FROM Tb002acesso t WHERE t.iduser.iduser = :id and t.tbacessotb000.idtabela = 2 ");
        query.setParameter("id", (Integer.parseInt(txtUser.getText())));
        List<Tb002acesso> data = query.getResultList();
        if (data.size() > 0) {
            String args[] = new String[4];
            args[0] = data.get(0).getInseriracesso().toString();
            args[1] = data.get(0).getEditaracesso().toString();
            args[2] = data.get(0).getExcluiracesso().toString();
            args[3] = data.get(0).getConsultaracesso().toString();
            txtInserir.setText(args[0]);
            txtEditar.setText(args[1]);
            txtExcluir.setText(args[2]);
            txtPesquisa.setText(args[3]);
            //Botao Inserir//////////////////////////////////////
            if (txtInserir.getText().equals("true")) {
                usuario.btnInserir.setEnabled(true);
            } else {
                usuario.btnInserir.setEnabled(false);
                //    fornecedor.txtMsg.setText("Sem Permissao ");
            }
            //  Botao Excluir/////////////////////////////////////////
            if (txtExcluir.getText().equals("true")) {
                usuario.btnExcluir.setEnabled(true);
            } else {
                usuario.btnExcluir.setEnabled(false);
            }
            //Botao Salvar - Planilhas/////////////////////////////////
            if (txtPesquisa.getText().equals("true")) {
                usuario.btnSalvar.setEnabled(true);
                usuario.txtPesq.setEnabled(true);
                usuario.tbUser.setEnabled(true);
            } else {
                usuario.btnSalvar.setEnabled(false);
                usuario.txtPesq.setEnabled(false);
                usuario.tbUser.setEnabled(false);
            }
            //  Botao Editar/////////////////////////////////////////
            if (txtEditar.getText().equals("true")) {
                usuario.txtPesq.setEnabled(true);
            } else {
                usuario.btnExcluir.setEnabled(false);
            }
            usuario.txtUsuario.setText(txtUser.getText());
            usuario.setVisible(true);

        } else {
            JOptionPane.showMessageDialog(null, "Sem acesso ao modulo!!");

        }
    }//GEN-LAST:event_btnUsuarioActionPerformed

    private void btnAcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcessoActionPerformed
        int user = (Integer.parseInt(txtUser.getText()));

        query = em.createQuery("SELECT t FROM Tb002acesso t WHERE t.iduser.iduser = :id and t.tbacessotb000.idtabela = 3 ");
        query.setParameter("id", (Integer.parseInt(txtUser.getText())));
        List<Tb002acesso> data = query.getResultList();
        if (data.size() > 0) {
            String args[] = new String[4];
            args[0] = data.get(0).getInseriracesso().toString();
            args[1] = data.get(0).getEditaracesso().toString();
            args[2] = data.get(0).getExcluiracesso().toString();
            args[3] = data.get(0).getConsultaracesso().toString();
            txtInserir.setText(args[0]);
            txtEditar.setText(args[1]);
            txtExcluir.setText(args[2]);
            txtPesquisa.setText(args[3]);
            //Botao Inserir//////////////////////////////////////
            if (txtInserir.getText().equals("true")) {
                acesso.btnInserir.setEnabled(true);
                //  fornecedor.txtMsg.setText("Com Permissao");
            } else {
                acesso.btnInserir.setEnabled(false);
                //    fornecedor.txtMsg.setText("Sem Permissao ");
            }
            //  Botao Excluir/////////////////////////////////////////
            if (txtExcluir.getText().equals("true")) {
                acesso.btnExcluir.setEnabled(true);
            } else {
                acesso.btnExcluir.setEnabled(false);
            }
            //Botao Salvar - Planilhas/////////////////////////////////
            if (txtPesquisa.getText().equals("true")) {
                acesso.btnSalvar.setEnabled(true);
                acesso.txtPesq.setEnabled(true);
                acesso.tbAcesso.setEnabled(true);
            } else {
                acesso.btnSalvar.setEnabled(false);
                acesso.txtPesq.setEnabled(false);
                acesso.tbAcesso.setEnabled(false);
            }
            //  Botao Editar/////////////////////////////////////////
            if (txtEditar.getText().equals("true")) {
                acesso.txtPesq.setEnabled(true);
            } else {
                acesso.btnExcluir.setEnabled(false);
            }
            acesso.setVisible(true);

        } else {
            JOptionPane.showMessageDialog(null, "Sem acesso ao modulo!!");

        }
    }//GEN-LAST:event_btnAcessoActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        //FECHA E LIBERA O SISTEMA PARA MAIS UM LOGIN DIFERENTE  
        queryLogado = em.createQuery("UPDATE Tb009logados t set t.numerologado = t.numerologado - 1 WHERE t.idlogado = 1");
        queryLogado.executeUpdate();
        em.getTransaction().commit();
        em.getTransaction().begin();
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnLogofActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogofActionPerformed
        //DESLOGA E LIBERA O SISTEMA PARA MAIS UM LOGIN DIFERENTE  

        queryLogado = em.createQuery("UPDATE Tb009logados t set t.numerologado = t.numerologado - 1 WHERE t.idlogado = 1");
        queryLogado.executeUpdate();
        em.getTransaction().commit();
        em.getTransaction().begin();
        //Faz o logof
        dispose();
        frmLogin.main(null);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogofActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        int user = (Integer.parseInt(txtUser.getText()));
        query = em.createQuery("SELECT t FROM Tb002acesso t WHERE t.iduser.iduser = :id and t.tbacessotb000.idtabela = 10 ");
        query.setParameter("id", (Integer.parseInt(txtUser.getText())));
        List<Tb002acesso> data = query.getResultList();
        if (data.size() > 0) {
            String args[] = new String[4];
            args[0] = data.get(0).getInseriracesso().toString();
            args[1] = data.get(0).getEditaracesso().toString();
            args[2] = data.get(0).getExcluiracesso().toString();
            args[3] = data.get(0).getConsultaracesso().toString();

            txtInserir.setText(args[0]);
            txtEditar.setText(args[1]);
            txtExcluir.setText(args[2]);
            txtPesquisa.setText(args[3]);

            //Botao Inserir//////////////////////////////////////
            if (txtInserir.getText().equals("true")) {
                logado.btnInserir.setEnabled(true);
                //  fornecedor.txtMsg.setText("Com Permissao");
            } else {
                logado.btnInserir.setEnabled(false);
                //    fornecedor.txtMsg.setText("Sem Permissao ");
            }
            //  Botao Excluir/////////////////////////////////////////
            if (txtExcluir.getText().equals("true")) {
                logado.btnExcluir.setEnabled(true);
            } else {
                logado.btnExcluir.setEnabled(false);
            }
            //Botao Salvar - Planilhas/////////////////////////////////
            if (txtPesquisa.getText().equals("true")) {
                logado.btnSalvar.setEnabled(true);
                //  logado.txtPesq.setEnabled(true);
                logado.tbLogados.setEnabled(true);
            } else {
                logado.btnSalvar.setEnabled(false);
                //   logado.txtPesq.setEnabled(false);
                logado.tbLogados.setEnabled(false);
            }
            //  Botao Editar/////////////////////////////////////////
            if (txtEditar.getText().equals("true")) {
                //   logado.txtPesq.setEnabled(true);
            } else {
                logado.btnExcluir.setEnabled(false);
            }
            logado.btnCancela.doClick();
            logado.setVisible(true);

        } else {
            JOptionPane.showMessageDialog(null, "Sem acesso ao modulo!!");

        }        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void menuLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLogActionPerformed
        int user = (Integer.parseInt(txtUser.getText()));
        query = em.createQuery("SELECT t FROM Tb002acesso t WHERE t.iduser.iduser = :id and t.tbacessotb000.idtabela = 11 ");
        query.setParameter("id", (Integer.parseInt(txtUser.getText())));
        List<Tb002acesso> data = query.getResultList();
        if (data.size() > 0) {
            String args[] = new String[4];
            args[0] = data.get(0).getInseriracesso().toString();
            args[1] = data.get(0).getEditaracesso().toString();
            args[2] = data.get(0).getExcluiracesso().toString();
            args[3] = data.get(0).getConsultaracesso().toString();

            txtInserir.setText(args[0]);
            txtEditar.setText(args[1]);
            txtExcluir.setText(args[2]);
            txtPesquisa.setText(args[3]);

            //Botao Inserir//////////////////////////////////////
            if (txtInserir.getText().equals("true")) {
                log.btnIncluir.setEnabled(true);
                //  fornecedor.txtMsg.setText("Com Permissao");
            } else {
                log.btnIncluir.setEnabled(false);
                //    fornecedor.txtMsg.setText("Sem Permissao ");
            }
            //  Botao Excluir/////////////////////////////////////////
            if (txtExcluir.getText().equals("true")) {
                log.btnExcluir.setEnabled(true);
            } else {
                log.btnExcluir.setEnabled(false);
            }
            //Botao Salvar - Planilhas/////////////////////////////////
            if (txtPesquisa.getText().equals("true")) {
                log.btnSalvar.setEnabled(true);
                //  logado.txtPesq.setEnabled(true);
                log.tbLog.setEnabled(true);
            } else {
                log.btnSalvar.setEnabled(false);
                //   logado.txtPesq.setEnabled(false);
                log.tbLog.setEnabled(false);
            }
            //  Botao Editar/////////////////////////////////////////
            if (txtEditar.getText().equals("true")) {
                //   logado.txtPesq.setEnabled(true);
            } else {
                log.btnExcluir.setEnabled(false);
            }
            log.btnCancela.doClick();
            log.setVisible(true);

        } else {
            JOptionPane.showMessageDialog(null, "Sem acesso ao modulo!!");

        }        // TODO add your h
    }//GEN-LAST:event_menuLogActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        int user = (Integer.parseInt(txtUser.getText()));
        query = em.createQuery("SELECT t FROM Tb002acesso t WHERE t.iduser.iduser = :id and t.tbacessotb000.idtabela = 7 ");
        query.setParameter("id", (Integer.parseInt(txtUser.getText())));
        List<Tb002acesso> data = query.getResultList();
        if (data.size() > 0) {
            String args[] = new String[4];
            args[0] = data.get(0).getInseriracesso().toString();
            args[1] = data.get(0).getEditaracesso().toString();
            args[2] = data.get(0).getExcluiracesso().toString();
            args[3] = data.get(0).getConsultaracesso().toString();

            txtInserir.setText(args[0]);
            txtEditar.setText(args[1]);
            txtExcluir.setText(args[2]);
            txtPesquisa.setText(args[3]);

            //Botao Inserir//////////////////////////////////////
            if (txtInserir.getText().equals("true")) {
                marca.btnIncluir.setEnabled(true);
                //  fornecedor.txtMsg.setText("Com Permissao");
            } else {
                marca.btnIncluir.setEnabled(false);
                //    fornecedor.txtMsg.setText("Sem Permissao ");
            }
            //  Botao Excluir/////////////////////////////////////////
            if (txtExcluir.getText().equals("true")) {
                marca.btnExcluir.setEnabled(true);
            } else {
                marca.btnExcluir.setEnabled(false);
            }
            //Botao Salvar - Planilhas/////////////////////////////////
            if (txtPesquisa.getText().equals("true")) {
                marca.btnSalvar.setEnabled(true);
                //  logado.txtPesq.setEnabled(true);
                marca.tbMarca.setEnabled(true);
            } else {
                marca.btnSalvar.setEnabled(false);
                //   logado.txtPesq.setEnabled(false);
                marca.tbMarca.setEnabled(false);
            }
            //  Botao Editar/////////////////////////////////////////
            if (txtEditar.getText().equals("true")) {
                //   logado.txtPesq.setEnabled(true);
            } else {
                marca.btnExcluir.setEnabled(false);
            }
            marca.txtUsuario.setText(txtUser.getText());
            //marca.btnCancela.doClick();
            marca.setVisible(true);

        } else {
            JOptionPane.showMessageDialog(null, "Sem acesso ao modulo!!");

        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        int user = (Integer.parseInt(txtUser.getText()));
        query = em.createQuery("SELECT t FROM Tb002acesso t WHERE t.iduser.iduser = :id and t.tbacessotb000.idtabela = 6 ");
        query.setParameter("id", (Integer.parseInt(txtUser.getText())));
        List<Tb002acesso> data = query.getResultList();
        if (data.size() > 0) {
            String args[] = new String[4];
            args[0] = data.get(0).getInseriracesso().toString();
            args[1] = data.get(0).getEditaracesso().toString();
            args[2] = data.get(0).getExcluiracesso().toString();
            args[3] = data.get(0).getConsultaracesso().toString();

            txtInserir.setText(args[0]);
            txtEditar.setText(args[1]);
            txtExcluir.setText(args[2]);
            txtPesquisa.setText(args[3]);

            //Botao Inserir//////////////////////////////////////
            if (txtInserir.getText().equals("true")) {
                un.btnIncluir.setEnabled(true);
                //  fornecedor.txtMsg.setText("Com Permissao");
            } else {
                un.btnIncluir.setEnabled(false);
                //    fornecedor.txtMsg.setText("Sem Permissao ");
            }
            //  Botao Excluir/////////////////////////////////////////
            if (txtExcluir.getText().equals("true")) {
                un.btnExcluir.setEnabled(true);
            } else {
                un.btnExcluir.setEnabled(false);
            }
            //Botao Salvar - Planilhas/////////////////////////////////
            if (txtPesquisa.getText().equals("true")) {
                un.btnSalvar.setEnabled(true);
                //  logado.txtPesq.setEnabled(true);
                un.tbUnidade.setEnabled(true);
            } else {
                un.btnSalvar.setEnabled(false);
                //   logado.txtPesq.setEnabled(false);
                un.tbUnidade.setEnabled(false);
            }
            //  Botao Editar/////////////////////////////////////////
            if (txtEditar.getText().equals("true")) {
                //   logado.txtPesq.setEnabled(true);
            } else {
                un.btnExcluir.setEnabled(false);
            }
            un.txtUsuario.setText(txtUser.getText());
            //marca.btnCancela.doClick();
            un.setVisible(true);

        } else {
            JOptionPane.showMessageDialog(null, "Sem acesso ao modulo!!");

        }                // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        int user = (Integer.parseInt(txtUser.getText()));
        query = em.createQuery("SELECT t FROM Tb002acesso t WHERE t.iduser.iduser = :id and t.tbacessotb000.idtabela = 5 ");
        query.setParameter("id", (Integer.parseInt(txtUser.getText())));
        List<Tb002acesso> data = query.getResultList();
        if (data.size() > 0) {
            String args[] = new String[4];
            args[0] = data.get(0).getInseriracesso().toString();
            args[1] = data.get(0).getEditaracesso().toString();
            args[2] = data.get(0).getExcluiracesso().toString();
            args[3] = data.get(0).getConsultaracesso().toString();

            txtInserir.setText(args[0]);
            txtEditar.setText(args[1]);
            txtExcluir.setText(args[2]);
            txtPesquisa.setText(args[3]);

            //Botao Inserir//////////////////////////////////////
            if (txtInserir.getText().equals("true")) {
                cat.btnInserir.setEnabled(true);
                //  fornecedor.txtMsg.setText("Com Permissao");
            } else {
                cat.btnInserir.setEnabled(false);
                //    fornecedor.txtMsg.setText("Sem Permissao ");
            }
            //  Botao Excluir/////////////////////////////////////////
            if (txtExcluir.getText().equals("true")) {
                cat.btnExcluir.setEnabled(true);
            } else {
                cat.btnExcluir.setEnabled(false);
            }
            //Botao Salvar - Planilhas/////////////////////////////////
            if (txtPesquisa.getText().equals("true")) {
                cat.btnSalvar.setEnabled(true);
                //  logado.txtPesq.setEnabled(true);
                cat.tbCategoria.setEnabled(true);
            } else {
                cat.btnSalvar.setEnabled(false);
                //   logado.txtPesq.setEnabled(false);
                cat.tbCategoria.setEnabled(false);
            }
            //  Botao Editar/////////////////////////////////////////
            if (txtEditar.getText().equals("true")) {
                //   logado.txtPesq.setEnabled(true);
            } else {
                cat.btnExcluir.setEnabled(false);
            }
            cat.txtUsuario.setText(txtUser.getText());
            //marca.btnCancela.doClick();
            cat.setVisible(true);

        } else {
            JOptionPane.showMessageDialog(null, "Sem acesso ao modulo!!");

        }                // T        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        int user = (Integer.parseInt(txtUser.getText()));
        query = em.createQuery("SELECT t FROM Tb002acesso t WHERE t.iduser.iduser = :id and t.tbacessotb000.idtabela = 8 ");
        query.setParameter("id", (Integer.parseInt(txtUser.getText())));
        List<Tb002acesso> data = query.getResultList();
        if (data.size() > 0) {
            String args[] = new String[4];
            args[0] = data.get(0).getInseriracesso().toString();
            args[1] = data.get(0).getEditaracesso().toString();
            args[2] = data.get(0).getExcluiracesso().toString();
            args[3] = data.get(0).getConsultaracesso().toString();

            txtInserir.setText(args[0]);
            txtEditar.setText(args[1]);
            txtExcluir.setText(args[2]);
            txtPesquisa.setText(args[3]);

            //Botao Inserir//////////////////////////////////////
            if (txtInserir.getText().equals("true")) {
                mod.btnIncluir.setEnabled(true);
                //  fornecedor.txtMsg.setText("Com Permissao");
            } else {
                mod.btnIncluir.setEnabled(false);
                //    fornecedor.txtMsg.setText("Sem Permissao ");
            }
            //  Botao Excluir/////////////////////////////////////////
            if (txtExcluir.getText().equals("true")) {
                mod.btnExcluir.setEnabled(true);
            } else {
                mod.btnExcluir.setEnabled(false);
            }
            //Botao Salvar - Planilhas/////////////////////////////////
            if (txtPesquisa.getText().equals("true")) {
                mod.btnSalvar.setEnabled(true);
                mod.txtPesq.setEnabled(true);
                mod.tbModelo.setEnabled(true);
            } else {
                mod.btnSalvar.setEnabled(false);
                mod.txtPesq.setEnabled(false);
                mod.tbModelo.setEnabled(false);
            }
            //  Botao Editar/////////////////////////////////////////
            if (txtEditar.getText().equals("true")) {
                mod.txtPesq.setEnabled(true);
            } else {
                mod.btnExcluir.setEnabled(false);
            }
            mod.txtUsuario.setText(txtUser.getText());
            mod.setVisible(true);

        } else {
            JOptionPane.showMessageDialog(null, "Sem acesso ao modulo!!");

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        int user = (Integer.parseInt(txtUser.getText()));
        query = em.createQuery("SELECT t FROM Tb002acesso t WHERE t.iduser.iduser = :id and t.tbacessotb000.idtabela = 4 ");
        query.setParameter("id", (Integer.parseInt(txtUser.getText())));
        List<Tb002acesso> data = query.getResultList();
        if (data.size() > 0) {
            String args[] = new String[4];
            args[0] = data.get(0).getInseriracesso().toString();
            args[1] = data.get(0).getEditaracesso().toString();
            args[2] = data.get(0).getExcluiracesso().toString();
            args[3] = data.get(0).getConsultaracesso().toString();

            txtInserir.setText(args[0]);
            txtEditar.setText(args[1]);
            txtExcluir.setText(args[2]);
            txtPesquisa.setText(args[3]);

            //Botao Inserir//////////////////////////////////////
            if (txtInserir.getText().equals("true")) {
                prod.btnIncluir.setEnabled(true);
                //  fornecedor.txtMsg.setText("Com Permissao");
            } else {
                prod.btnIncluir.setEnabled(false);
                //    fornecedor.txtMsg.setText("Sem Permissao ");
            }
            //  Botao Excluir/////////////////////////////////////////
            if (txtExcluir.getText().equals("true")) {
                prod.btnExcluir.setEnabled(true);
            } else {
                prod.btnExcluir.setEnabled(false);
            }
            //Botao Salvar - Planilhas/////////////////////////////////
            if (txtPesquisa.getText().equals("true")) {
                prod.btnSalvar.setEnabled(true);
                prod.txtPesq.setEnabled(true);
                prod.tbProduto.setEnabled(true);
            } else {
                prod.btnSalvar.setEnabled(false);
                prod.txtPesq.setEnabled(false);
                prod.tbProduto.setEnabled(false);
            }
            //  Botao Editar/////////////////////////////////////////
            if (txtEditar.getText().equals("true")) {
                prod.txtPesq.setEnabled(true);
            } else {
                prod.btnExcluir.setEnabled(false);
            }
            prod.txtUsuario.setText(txtUser.getText());
            prod.setVisible(true);

        } else {
            JOptionPane.showMessageDialog(null, "Sem acesso ao modulo!!");

        }      // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        int user = (Integer.parseInt(txtUser.getText()));
        query = em.createQuery("SELECT t FROM Tb002acesso t WHERE t.iduser.iduser = :id and t.tbacessotb000.idtabela = 1");
        query.setParameter("id", (Integer.parseInt(txtUser.getText())));
        List<Tb002acesso> data = query.getResultList();
        if (data.size() > 0) {
            String args[] = new String[4];
            args[0] = data.get(0).getInseriracesso().toString();
            args[1] = data.get(0).getEditaracesso().toString();
            args[2] = data.get(0).getExcluiracesso().toString();
            args[3] = data.get(0).getConsultaracesso().toString();

            txtInserir.setText(args[0]);
            txtEditar.setText(args[1]);
            txtExcluir.setText(args[2]);
            txtPesquisa.setText(args[3]);

            //Botao Inserir//////////////////////////////////////
            if (txtInserir.getText().equals("true")) {
                tab.btnIncluir.setEnabled(true);
                //  fornecedor.txtMsg.setText("Com Permissao");
            } else {
                tab.btnIncluir.setEnabled(false);
                //    fornecedor.txtMsg.setText("Sem Permissao ");
            }
            //  Botao Excluir/////////////////////////////////////////
            if (txtExcluir.getText().equals("true")) {
                tab.btnExcluir.setEnabled(true);
            } else {
                tab.btnExcluir.setEnabled(false);
            }
            //Botao Salvar - Planilhas/////////////////////////////////
            if (txtPesquisa.getText().equals("true")) {
                tab.btnSalvar.setEnabled(true);
                tab.txtPesq.setEnabled(true);
                tab.tbTabela.setEnabled(true);
            } else {
                tab.btnSalvar.setEnabled(false);
                tab.txtPesq.setEnabled(false);
                tab.tbTabela.setEnabled(false);
            }
            //  Botao Editar/////////////////////////////////////////
            if (txtEditar.getText().equals("true")) {
                tab.txtPesq.setEnabled(true);
            } else {
                tab.btnExcluir.setEnabled(false);
            }
            tab.txtUsuario.setText(txtUser.getText());
            tab.setVisible(true);

        } else {
            JOptionPane.showMessageDialog(null, "Sem acesso ao modulo!!");

        }
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void menuLojaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLojaActionPerformed
        int user = (Integer.parseInt(txtUser.getText()));
        query = em.createQuery("SELECT t FROM Tb002acesso t WHERE t.iduser.iduser = :id and t.tbacessotb000.idtabela = 12 ");
        query.setParameter("id", (Integer.parseInt(txtUser.getText())));
        List<Tb002acesso> data = query.getResultList();
        if (data.size() > 0) {
            String args[] = new String[4];
            args[0] = data.get(0).getInseriracesso().toString();
            args[1] = data.get(0).getEditaracesso().toString();
            args[2] = data.get(0).getExcluiracesso().toString();
            args[3] = data.get(0).getConsultaracesso().toString();

            txtInserir.setText(args[0]);
            txtEditar.setText(args[1]);
            txtExcluir.setText(args[2]);
            txtPesquisa.setText(args[3]);

            //Botao Inserir//////////////////////////////////////
            if (txtInserir.getText().equals("true")) {
                loja.btnNovo.setEnabled(true);
                //  fornecedor.txtMsg.setText("Com Permissao");
            } else {
                loja.btnNovo.setEnabled(false);
                //    fornecedor.txtMsg.setText("Sem Permissao ");
            }
            //  Botao Excluir/////////////////////////////////////////
            if (txtExcluir.getText().equals("true")) {
                loja.btnDelete.setEnabled(true);
            } else {
                loja.btnDelete.setEnabled(false);
            }
            //Botao Salvar - Planilhas/////////////////////////////////
            if (txtPesquisa.getText().equals("true")) {
                loja.btnSalvar.setEnabled(true);
                //  logado.txtPesq.setEnabled(true);
                loja.tbLojas.setEnabled(true);
            } else {
                loja.btnSalvar.setEnabled(false);
                //   logado.txtPesq.setEnabled(false);
                loja.tbLojas.setEnabled(false);
            }
            //  Botao Editar/////////////////////////////////////////
            if (txtEditar.getText().equals("true")) {
                //   logado.txtPesq.setEnabled(true);
            } else {
                loja.btnDelete.setEnabled(false);
            }
           // loja.btnCancela.doClick();
            loja.txtUsuario.setText(txtUser.getText());
            loja.setVisible(true);

        } else {
            JOptionPane.showMessageDialog(null, "Sem acesso ao modulo!!");

        }        // TODO add your h        // TODO add your handling code here:
    }//GEN-LAST:event_menuLojaActionPerformed

    private void menuVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVendaActionPerformed
        int user = (Integer.parseInt(txtUser.getText()));
        query = em.createQuery("SELECT t FROM Tb002acesso t WHERE t.iduser.iduser = :id and t.tbacessotb000.idtabela = 13 ");
        query.setParameter("id", (Integer.parseInt(txtUser.getText())));
        List<Tb002acesso> data = query.getResultList();
        if (data.size() > 0) {
            String args[] = new String[4];
            args[0] = data.get(0).getInseriracesso().toString();
            args[1] = data.get(0).getEditaracesso().toString();
            args[2] = data.get(0).getExcluiracesso().toString();
            args[3] = data.get(0).getConsultaracesso().toString();

            txtInserir.setText(args[0]);
            txtEditar.setText(args[1]);
            txtExcluir.setText(args[2]);
            txtPesquisa.setText(args[3]);

            //Botao Inserir//////////////////////////////////////
            if (txtInserir.getText().equals("true")) {
                venda.btnIncluir.setEnabled(true);
                //  fornecedor.txtMsg.setText("Com Permissao");
            } else {
                venda.btnIncluir.setEnabled(false);
                //    fornecedor.txtMsg.setText("Sem Permissao ");
            }
            //  Botao Excluir/////////////////////////////////////////
            if (txtExcluir.getText().equals("true")) {
                venda.btnExcluir.setEnabled(true);
            } else {
                venda.btnExcluir.setEnabled(false);
            }
            //Botao Salvar - Planilhas/////////////////////////////////
            if (txtPesquisa.getText().equals("true")) {
                venda.btnSalvar.setEnabled(true);
                //  logado.txtPesq.setEnabled(true);
                venda.tbVenda.setEnabled(true);
            } else {
                venda.btnSalvar.setEnabled(false);
                //   logado.txtPesq.setEnabled(false);
                venda.tbVenda.setEnabled(false);
            }
            //  Botao Editar/////////////////////////////////////////
            if (txtEditar.getText().equals("true")) {
                //   logado.txtPesq.setEnabled(true);
            } else {
                venda.btnExcluir.setEnabled(false);
            }
           // loja.btnCancela.doClick();
            venda.txtUsuario.setText(txtUser.getText());
            venda.setVisible(true);

        } else {
            JOptionPane.showMessageDialog(null, "Sem acesso ao modulo!!");

        }
    }//GEN-LAST:event_menuVendaActionPerformed

    private void menuVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVendedorActionPerformed
        int user = (Integer.parseInt(txtUser.getText()));
        query = em.createQuery("SELECT t FROM Tb002acesso t WHERE t.iduser.iduser = :id and t.tbacessotb000.idtabela = 14 ");
        query.setParameter("id", (Integer.parseInt(txtUser.getText())));
        List<Tb002acesso> data = query.getResultList();
        if (data.size() > 0) {
            String args[] = new String[4];
            args[0] = data.get(0).getInseriracesso().toString();
            args[1] = data.get(0).getEditaracesso().toString();
            args[2] = data.get(0).getExcluiracesso().toString();
            args[3] = data.get(0).getConsultaracesso().toString();

            txtInserir.setText(args[0]);
            txtEditar.setText(args[1]);
            txtExcluir.setText(args[2]);
            txtPesquisa.setText(args[3]);

            //Botao Inserir//////////////////////////////////////
            if (txtInserir.getText().equals("true")) {
                vend.btnIncluir.setEnabled(true);
                //  fornecedor.txtMsg.setText("Com Permissao");
            } else {
                vend.btnIncluir.setEnabled(false);
                //    fornecedor.txtMsg.setText("Sem Permissao ");
            }
            //  Botao Excluir/////////////////////////////////////////
            if (txtExcluir.getText().equals("true")) {
                vend.btnExcluir.setEnabled(true);
            } else {
                vend.btnExcluir.setEnabled(false);
            }
            //Botao Salvar - Planilhas/////////////////////////////////
            if (txtPesquisa.getText().equals("true")) {
                vend.btnSalvar.setEnabled(true);
                //  logado.txtPesq.setEnabled(true);
                vend.tbVendas.setEnabled(true);
            } else {
                vend.btnSalvar.setEnabled(false);
                //   logado.txtPesq.setEnabled(false);
                vend.tbVendas.setEnabled(false);
            }
            //  Botao Editar/////////////////////////////////////////
            if (txtEditar.getText().equals("true")) {
                //   logado.txtPesq.setEnabled(true);
            } else {
                vend.btnExcluir.setEnabled(false);
            }
           // loja.btnCancela.doClick();
            vend.txtUsuario.setText(txtUser.getText());
            vend.setVisible(true);

        } else {
            JOptionPane.showMessageDialog(null, "Sem acesso ao modulo!!");

        }
    }//GEN-LAST:event_menuVendedorActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        int user = (Integer.parseInt(txtUser.getText()));
        query = em.createQuery("SELECT t FROM Tb002acesso t WHERE t.iduser.iduser = :id and t.tbacessotb000.idtabela = 15 ");
        query.setParameter("id", (Integer.parseInt(txtUser.getText())));
        List<Tb002acesso> data = query.getResultList();
        if (data.size() > 0) {
            String args[] = new String[4];
            args[0] = data.get(0).getInseriracesso().toString();
            args[1] = data.get(0).getEditaracesso().toString();
            args[2] = data.get(0).getExcluiracesso().toString();
            args[3] = data.get(0).getConsultaracesso().toString();

            txtInserir.setText(args[0]);
            txtEditar.setText(args[1]);
            txtExcluir.setText(args[2]);
            txtPesquisa.setText(args[3]);

            //Botao Inserir//////////////////////////////////////
            if (txtInserir.getText().equals("true")) {
                boleto.btnIncluir.setEnabled(true);
                //  fornecedor.txtMsg.setText("Com Permissao");
            } else {
                boleto.btnIncluir.setEnabled(false);
                //    fornecedor.txtMsg.setText("Sem Permissao ");
            }
            //  Botao Excluir/////////////////////////////////////////
            if (txtExcluir.getText().equals("true")) {
                boleto.btnExcluir.setEnabled(true);
            } else {
                boleto.btnExcluir.setEnabled(false);
            }
            //Botao Salvar - Planilhas/////////////////////////////////
            if (txtPesquisa.getText().equals("true")) {
                boleto.btnSalvar.setEnabled(true);
                //  logado.txtPesq.setEnabled(true);
                boleto.tbBoletas.setEnabled(true);
            } else {
                boleto.btnSalvar.setEnabled(false);
                //   logado.txtPesq.setEnabled(false);
                boleto.tbBoletas.setEnabled(false);
            }
            //  Botao Editar/////////////////////////////////////////
            if (txtEditar.getText().equals("true")) {
                //   logado.txtPesq.setEnabled(true);
            } else {
                boleto.btnExcluir.setEnabled(false);
            }
           // loja.btnCancela.doClick();
            boleto.txtUsuario.setText(txtUser.getText());
            boleto.setVisible(true);

        } else {
            JOptionPane.showMessageDialog(null, "Sem acesso ao modulo!!");

        }
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jmOcorrenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmOcorrenciaActionPerformed
        int user = (Integer.parseInt(txtUser.getText()));
        query = em.createQuery("SELECT t FROM Tb002acesso t WHERE t.iduser.iduser = :id and t.tbacessotb000.idtabela = 16 ");
        query.setParameter("id", (Integer.parseInt(txtUser.getText())));
        List<Tb002acesso> data = query.getResultList();
      
        if (data.size() > 0) {
            String args[] = new String[4];
            args[0] = data.get(0).getInseriracesso().toString();
            args[1] = data.get(0).getEditaracesso().toString();
            args[2] = data.get(0).getExcluiracesso().toString();
            args[3] = data.get(0).getConsultaracesso().toString();

            txtInserir.setText(args[0]);
            txtEditar.setText(args[1]);
            txtExcluir.setText(args[2]);
            txtPesquisa.setText(args[3]);

            //Botao Inserir//////////////////////////////////////
            if (txtInserir.getText().equals("true")) {
                ocorrencia.btnIncluir.setEnabled(true);
                //  fornecedor.txtMsg.setText("Com Permissao");
            } else {
                ocorrencia.btnIncluir.setEnabled(false);
                //    fornecedor.txtMsg.setText("Sem Permissao ");
            }
            //  Botao Excluir/////////////////////////////////////////
            if (txtExcluir.getText().equals("true")) {
                ocorrencia.btnExcluir.setEnabled(true);
            } else {
                ocorrencia.btnExcluir.setEnabled(false);
            }
            //Botao Salvar - Planilhas/////////////////////////////////
            if (txtPesquisa.getText().equals("true")) {
                ocorrencia.btnSalvar.setEnabled(true);
                //  logado.txtPesq.setEnabled(true);
                ocorrencia.tbOcorrencia.setEnabled(true);
            } else {
                ocorrencia.btnSalvar.setEnabled(false);
                //   logado.txtPesq.setEnabled(false);
                ocorrencia.tbOcorrencia.setEnabled(false);
            }
            //  Botao Editar/////////////////////////////////////////
            if (txtEditar.getText().equals("true")) {
                //   logado.txtPesq.setEnabled(true);
            } else {
                ocorrencia.btnExcluir.setEnabled(false);
            }
           // loja.btnCancela.doClick();
            ocorrencia.txtUsuario.setText(txtUser.getText());
            ocorrencia.setVisible(true);

        } else {
            JOptionPane.showMessageDialog(null, "Sem acesso ao modulo!!");

        }
    }//GEN-LAST:event_jmOcorrenciaActionPerformed

    private void menuCadFichaConsertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadFichaConsertoActionPerformed
       btnFicha.doClick();
    }//GEN-LAST:event_menuCadFichaConsertoActionPerformed

    private void btnCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCliActionPerformed
        int user = (Integer.parseInt(txtUser.getText()));
        query = em.createQuery("SELECT t FROM Tb002acesso t WHERE t.iduser.iduser = :id and t.tbacessotb000.idtabela = 26");
        query.setParameter("id", (Integer.parseInt(txtUser.getText())));
        List<Tb002acesso> data = query.getResultList();
        if (data.size() > 0) {
            String args[] = new String[4];
            args[0] = data.get(0).getInseriracesso().toString();
            args[1] = data.get(0).getEditaracesso().toString();
            args[2] = data.get(0).getExcluiracesso().toString();
            args[3] = data.get(0).getConsultaracesso().toString();

            txtInserir.setText(args[0]);
            txtEditar.setText(args[1]);
            txtExcluir.setText(args[2]);
            txtPesquisa.setText(args[3]);

            //Botao Inserir//////////////////////////////////////
            if (txtInserir.getText().equals("true")) {
                cliente.btnIncluir.setEnabled(true);
                //  fornecedor.txtMsg.setText("Com Permissao");
            } else {
                cliente.btnIncluir.setEnabled(false);
                //    fornecedor.txtMsg.setText("Sem Permissao ");
            }
            //  Botao Excluir/////////////////////////////////////////
            if (txtExcluir.getText().equals("true")) {
                cliente.btnExcluir.setEnabled(true);
            } else {
                cliente.btnExcluir.setEnabled(false);
            }
            //Botao Salvar - Planilhas/////////////////////////////////
            if (txtPesquisa.getText().equals("true")) {
                cliente.btnSalvar.setEnabled(true);
                //  logado.txtPesq.setEnabled(true);
                cliente.tbCliLojas.setEnabled(true);
            } else {
                cliente.btnSalvar.setEnabled(false);
                //   logado.txtPesq.setEnabled(false);
                cliente.tbCliLojas.setEnabled(false);
            }
            //  Botao Editar/////////////////////////////////////////
            if (txtEditar.getText().equals("true")) {
                //   logado.txtPesq.setEnabled(true);
            } else {
                cliente.btnExcluir.setEnabled(false);
            }
           // loja.btnCancela.doClick();
            cliente.txtUsuario.setText(txtUser.getText());
            cliente.setVisible(true);

        } else {
            JOptionPane.showMessageDialog(null, "Sem acesso ao modulo!!");

        }           // TODO add your handling code here:
    }//GEN-LAST:event_btnCliActionPerformed

    private void btnFichaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFichaActionPerformed
        int user = (Integer.parseInt(txtUser.getText()));
      
        query = em.createQuery("SELECT t FROM Tb002acesso t WHERE t.iduser.iduser = :id and t.tbacessotb000.idtabela = 20");
        query.setParameter("id", (Integer.parseInt(txtUser.getText())));
        List<Tb002acesso> data = query.getResultList();
        if (data.size() > 0) {
            String args[] = new String[4];
            args[0] = data.get(0).getInseriracesso().toString();
            args[1] = data.get(0).getEditaracesso().toString();
            args[2] = data.get(0).getExcluiracesso().toString();
            args[3] = data.get(0).getConsultaracesso().toString();

            txtInserir.setText(args[0]);
            txtEditar.setText(args[1]);
            txtExcluir.setText(args[2]);
            txtPesquisa.setText(args[3]);

            //Botao Inserir//////////////////////////////////////
            if (txtInserir.getText().equals("true")) {
                ficha.btnIncluir.setEnabled(true);
                //  fornecedor.txtMsg.setText("Com Permissao");
            } else {
                ficha.btnIncluir.setEnabled(false);
                //    fornecedor.txtMsg.setText("Sem Permissao ");
            }
            //  Botao Excluir/////////////////////////////////////////
            if (txtExcluir.getText().equals("true")) {
                ficha.btnExcluir.setEnabled(true);
            } else {
                ficha.btnExcluir.setEnabled(false);
            }
            //Botao Salvar - Planilhas/////////////////////////////////
            if (txtPesquisa.getText().equals("true")) {
                ficha.btnSalvar.setEnabled(true);
                //  logado.txtPesq.setEnabled(true);
                ficha.tbFicha.setEnabled(true);
            } else {
                ficha.btnSalvar.setEnabled(false);
                //   logado.txtPesq.setEnabled(false);
                ficha.tbFicha.setEnabled(false);
            }
            //  Botao Editar/////////////////////////////////////////
            if (txtEditar.getText().equals("true")) {
                //   logado.txtPesq.setEnabled(true);
            } else {
                ficha.btnExcluir.setEnabled(false);
            }
           // loja.btnCancela.doClick();
            ficha.txtUsuario.setText(txtUser.getText());
            ficha.setVisible(true);

        } else {
            JOptionPane.showMessageDialog(null, "Sem acesso ao modulo!!");

        }               // TODO add your handling code here:
    }//GEN-LAST:event_btnFichaActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
      btnCli.doClick();        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows Classic".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
                txtUsuario.setText("Logado no Sistema:  " + args[0] + " ----  Registro Nº : " + args[1]);
                txtUser.setText(args[1]);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcesso;
    private javax.swing.JButton btnCli;
    private javax.swing.JButton btnFicha;
    private javax.swing.JButton btnFornecedor;
    private javax.swing.JButton btnLogof;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnUsuario;
    private javax.persistence.EntityManager em;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenuItem jmOcorrencia;
    private javax.swing.JMenu jmVendas;
    private javax.swing.JPanel jpConserto;
    private javax.swing.JPanel jpMenu;
    private javax.swing.JPanel jpSeparador;
    private java.awt.Panel jpanelInferior;
    private java.util.List<com.guina.model.Tb002acesso> list;
    private java.util.List<com.guina.model.Tb009logados> listLogado;
    private javax.swing.JMenuItem menuCadFichaConserto;
    private javax.swing.JMenu menuConserto;
    private javax.swing.JMenuItem menuLog;
    private javax.swing.JMenuItem menuLoja;
    private javax.swing.JMenuItem menuVenda;
    private javax.swing.JMenuItem menuVendedor;
    private javax.persistence.Query query;
    private javax.persistence.Query queryLogado;
    private javax.swing.JLabel txtEditar;
    private javax.swing.JLabel txtExcluir;
    private javax.swing.JLabel txtInserir;
    private javax.swing.JLabel txtPesquisa;
    private static javax.swing.JLabel txtUser;
    private static javax.swing.JLabel txtUsuario;
    // End of variables declaration//GEN-END:variables

}
