/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.guina.view;

import com.guina.model.Tb001user;
import com.guina.model.Tb013vendedoras;
import com.guina.uteis.uteis;
import java.beans.Beans;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.RollbackException;
import javax.swing.JTable;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Agnaldo
 */
public class frmVendedorasTb013 extends javax.swing.JDialog {

     //////nome da tabela////////
    String tb = "tb013vendedoras";
    String acao,aux;// aux variavel da funcao Id
    int n,novo; // variavel da funcao Id
    /////////////////////////
    public frmVendedorasTb013(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
         if (!Beans.isDesignTime()) {
            em.getTransaction().begin();
        }
        //COLOCAR BARRA HORIZONTAL - TABELA ITENS
        tbVendas.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        //ORGANIZAR TABELA MODO CRESCENTE OU DECRESCENTE - TABELA DE ITENS
        TableModel modelo = (TableModel) tbVendas.getModel();
        tbVendas.setRowSorter(new TableRowSorter(modelo));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        em = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("permissaoPU").createEntityManager();
        query = java.beans.Beans.isDesignTime() ? null : em.createQuery("SELECT t FROM Tb013vendedoras t");
        list = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(query.getResultList());
        queryLoja = java.beans.Beans.isDesignTime() ? null : em.createQuery("SELECT t FROM Tb011lojas t");
        listLoja = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(queryLoja.getResultList());
        tb013vendedorasQuery = java.beans.Beans.isDesignTime() ? null : em.createQuery("SELECT t FROM Tb013vendedoras t");
        tb013vendedorasList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : tb013vendedorasQuery.getResultList();
        queryUser = java.beans.Beans.isDesignTime() ? null : em.createQuery("SELECT t FROM Tb001user t");
        listUser = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(queryUser.getResultList());
        queryLog = java.beans.Beans.isDesignTime() ? null : em.createQuery("SELECT t FROM Tb010logsistema t");
        listLog = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(queryLog.getResultList());
        jpDados = new javax.swing.JPanel();
        txtNome = new javax.swing.JTextField();
        idlojavendedorLabel = new javax.swing.JLabel();
        nomevendedorLabel = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jcLoja = new javax.swing.JComboBox<>();
        idvendedorLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        masterScrollPane = new javax.swing.JScrollPane();
        tbVendas = new javax.swing.JTable();
        jpBotoes = new javax.swing.JPanel();
        btnExcluir = new javax.swing.JButton();
        btnIncluir = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnCancela = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        txtPesq = new javax.swing.JTextField();
        jpLog = new javax.swing.JPanel();
        txtIdItem = new javax.swing.JTextField();
        txtItem = new javax.swing.JTextField();
        txtUser = new javax.swing.JTextField();
        txtData = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtHora = new javax.swing.JTextField();
        txtAcao = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ITEM = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        masterScrollPane1 = new javax.swing.JScrollPane();
        tbLog = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnSalvarLog = new javax.swing.JButton();
        btnCancelaLog = new javax.swing.JButton();
        btnNovoLog = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtTabela = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Vendedor");
        setResizable(false);

        jpDados.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tbVendas, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.nomevendedor}"), txtNome, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tbVendas, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), txtNome, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        txtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNomeKeyReleased(evt);
            }
        });

        idlojavendedorLabel.setText("Loja:");

        nomevendedorLabel.setText("Nome:");

        txtId.setEditable(false);
        txtId.setBackground(new java.awt.Color(153, 204, 255));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tbVendas, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.idvendedor}"), txtId, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tbVendas, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), txtId, org.jdesktop.beansbinding.BeanProperty.create("focusable"));
        bindingGroup.addBinding(binding);

        org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, listLoja, jcLoja);
        bindingGroup.addBinding(jComboBoxBinding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tbVendas, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.idlojavendedor}"), jcLoja, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tbVendas, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), jcLoja, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        idvendedorLabel.setText("ID:");

        jButton1.setText("...");

        javax.swing.GroupLayout jpDadosLayout = new javax.swing.GroupLayout(jpDados);
        jpDados.setLayout(jpDadosLayout);
        jpDadosLayout.setHorizontalGroup(
            jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idvendedorLabel)
                    .addComponent(nomevendedorLabel)
                    .addComponent(idlojavendedorLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNome)
                    .addGroup(jpDadosLayout.createSequentialGroup()
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jpDadosLayout.createSequentialGroup()
                        .addComponent(jcLoja, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpDadosLayout.setVerticalGroup(
            jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idvendedorLabel)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomevendedorLabel)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idlojavendedorLabel)
                    .addComponent(jcLoja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, list, tbVendas);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${idvendedor}"));
        columnBinding.setColumnName("ID");
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nomevendedor}"));
        columnBinding.setColumnName("Vendedor");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${idlojavendedor}"));
        columnBinding.setColumnName("Loja");
        columnBinding.setColumnClass(com.guina.model.Tb011lojas.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        tbVendas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbVendasMouseClicked(evt);
            }
        });
        masterScrollPane.setViewportView(tbVendas);
        if (tbVendas.getColumnModel().getColumnCount() > 0) {
            tbVendas.getColumnModel().getColumn(0).setMinWidth(30);
            tbVendas.getColumnModel().getColumn(0).setMaxWidth(30);
            tbVendas.getColumnModel().getColumn(1).setMinWidth(140);
            tbVendas.getColumnModel().getColumn(1).setMaxWidth(200);
            tbVendas.getColumnModel().getColumn(2).setMinWidth(200);
            tbVendas.getColumnModel().getColumn(2).setMaxWidth(200);
        }

        jpBotoes.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jpBotoes.setLayout(new java.awt.GridLayout(1, 0));

        btnExcluir.setText("Delete");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        jpBotoes.add(btnExcluir);

        btnIncluir.setText("Novo");
        btnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirActionPerformed(evt);
            }
        });
        jpBotoes.add(btnIncluir);

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        jpBotoes.add(btnSalvar);

        btnCancela.setText("Cancela");
        btnCancela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelaActionPerformed(evt);
            }
        });
        jpBotoes.add(btnCancela);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Pesquisa...", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));
        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        txtPesq.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesqKeyReleased(evt);
            }
        });
        jPanel4.add(txtPesq);

        jpLog.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Log"));

        txtIdItem.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tbLog, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.iditemlog}"), txtIdItem, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        txtItem.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tbLog, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.itemnomelog}"), txtItem, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        txtUser.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tbLog, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.usuerlog}"), txtUser, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        txtUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUserFocusGained(evt);
            }
        });

        txtData.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tbLog, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.datalogo}"), txtData, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        txtUsuario.setText("USUARIO");

        jLabel1.setText("USER:");

        jLabel5.setText("AÇÃO");

        txtHora.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tbLog, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.horalog}"), txtHora, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        txtAcao.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tbLog, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.acaolog}"), txtAcao, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jLabel2.setText("DATA:");

        ITEM.setText("ID ITEM");

        jLabel4.setText("TABELA:");

        jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, listLog, tbLog);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${itemnomelog}"));
        columnBinding.setColumnName("Itemnomelog");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${iditemlog}"));
        columnBinding.setColumnName("Iditemlog");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${acaolog}"));
        columnBinding.setColumnName("Acaolog");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${tablog}"));
        columnBinding.setColumnName("Tablog");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${usuerlog}"));
        columnBinding.setColumnName("Usuerlog");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${horalog}"));
        columnBinding.setColumnName("Horalog");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${datalogo}"));
        columnBinding.setColumnName("Datalogo");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${idlog}"));
        columnBinding.setColumnName("Idlog");
        columnBinding.setColumnClass(Integer.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        masterScrollPane1.setViewportView(tbLog);

        jLabel6.setText("ITEM_");

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        btnSalvarLog.setText("SalvarLog");
        btnSalvarLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarLogActionPerformed(evt);
            }
        });
        jPanel3.add(btnSalvarLog);

        btnCancelaLog.setText("RefreshLog");
        btnCancelaLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelaLogActionPerformed(evt);
            }
        });
        jPanel3.add(btnCancelaLog);

        btnNovoLog.setText("NovoLog");
        btnNovoLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoLogActionPerformed(evt);
            }
        });
        jPanel3.add(btnNovoLog);

        jLabel3.setText("HORA:");

        txtTabela.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tbLog, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.tablog}"), txtTabela, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout jpLogLayout = new javax.swing.GroupLayout(jpLog);
        jpLog.setLayout(jpLogLayout);
        jpLogLayout.setHorizontalGroup(
            jpLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpLogLayout.createSequentialGroup()
                        .addGroup(jpLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addGroup(jpLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jpLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpLogLayout.createSequentialGroup()
                                .addComponent(ITEM)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIdItem, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jpLogLayout.createSequentialGroup()
                                .addGroup(jpLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpLogLayout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtAcao, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtUsuario))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jpLogLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(txtTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtItem, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpLogLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(masterScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jpLogLayout.setVerticalGroup(
            jpLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(masterScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jpLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpLogLayout.createSequentialGroup()
                        .addGroup(jpLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpLogLayout.createSequentialGroup()
                        .addGroup(jpLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtAcao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jpLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(ITEM)
                    .addComponent(txtIdItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jpLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTabela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(txtItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpDados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jpBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(masterScrollPane))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpLog, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jpLog, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(masterScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        setSize(new java.awt.Dimension(516, 390));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        acao = ("Excluir");
        
        int[] selected = tbVendas.getSelectedRows();
        List<com.guina.model.Tb013vendedoras> toRemove = new ArrayList<com.guina.model.Tb013vendedoras>(selected.length);
        for (int idx = 0; idx < selected.length; idx++) {
            com.guina.model.Tb013vendedoras t = list.get(tbVendas.convertRowIndexToModel(selected[idx]));
            toRemove.add(t);
            em.remove(t);
        }
        list.removeAll(toRemove);
         //Depois de deletar Salva
        btnSalvar.doClick();
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirActionPerformed
        txtNome.requestFocus();
       //recebe  a ação incluir
        MaxId();//função verifica o ultimo id
        acao = ("Incluir");
        
        //////////////////////////////////////////////////////////////////
        com.guina.model.Tb013vendedoras t = new com.guina.model.Tb013vendedoras();
        em.persist(t);
        list.add(t);
        int row = list.size() - 1;
        tbVendas.setRowSelectionInterval(row, row);
        tbVendas.scrollRectToVisible(tbVendas.getCellRect(row, 0, true));
        
        txtId.setText(Integer.toString(novo));
    }//GEN-LAST:event_btnIncluirActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
         //inicia função de Log
        btnNovoLog.doClick();//incia o log
        Dados();//Preenche dados
        User();//Pega Usuario
        btnSalvarLog.doClick();//Salva na tabela de log
        btnCancelaLog.doClick();//Atualiza tabela de Log
        
        try {
            em.getTransaction().commit();
            em.getTransaction().begin();
        } catch (RollbackException rex) {
            rex.printStackTrace();
            em.getTransaction().begin();
            List<com.guina.model.Tb013vendedoras> merged = new ArrayList<com.guina.model.Tb013vendedoras>(list.size());
            for (com.guina.model.Tb013vendedoras t : list) {
                merged.add(em.merge(t));
            }
            list.clear();
            list.addAll(merged);
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelaActionPerformed
        em.getTransaction().rollback();
        em.getTransaction().begin();
        java.util.Collection data = query.getResultList();
        for (Object entity : data) {
            em.refresh(entity);
        }
        list.clear();
        list.addAll(data);
    }//GEN-LAST:event_btnCancelaActionPerformed

    private void txtPesqKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesqKeyReleased
        uteis.maiscula(evt);
        query = em.createQuery("SELECT t FROM Tb013vendedoras t WHERE t.nomevendedor LIKE :nome ");
        query.setParameter("nome", "%" + txtPesq.getText() + "%");
        list.clear();
        list.addAll(query.getResultList());  // TODO add your handling code here:
    }//GEN-LAST:event_txtPesqKeyReleased

    private void txtNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyReleased
       uteis.maiscula(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeKeyReleased

    private void txtUserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserFocusGained

    private void btnSalvarLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarLogActionPerformed
        try {
            em.getTransaction().commit();
            em.getTransaction().begin();
        } catch (RollbackException rex) {
            rex.printStackTrace();
            em.getTransaction().begin();
            List<com.guina.model.Tb010logsistema> merged = new ArrayList<com.guina.model.Tb010logsistema>(listLog.size());
            for (com.guina.model.Tb010logsistema t : listLog) {
                merged.add(em.merge(t));
            }
            listLog.clear();
            listLog.addAll(merged);
        }
    }//GEN-LAST:event_btnSalvarLogActionPerformed

    private void btnCancelaLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelaLogActionPerformed
        em.getTransaction().rollback();
        em.getTransaction().begin();
        java.util.Collection data = queryLog.getResultList();
        for (Object entity : data) {
            em.refresh(entity);
        }
        listLog.clear();
        listLog.addAll(data);
    }//GEN-LAST:event_btnCancelaLogActionPerformed

    private void btnNovoLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoLogActionPerformed
        com.guina.model.Tb010logsistema t = new com.guina.model.Tb010logsistema();
        em.persist(t);
        listLog.add(t);
        int row = listLog.size() - 1;
        tbLog.setRowSelectionInterval(row, row);
        tbLog.scrollRectToVisible(tbLog.getCellRect(row, 0, true));
    }//GEN-LAST:event_btnNovoLogActionPerformed

    private void tbVendasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbVendasMouseClicked
       acao = ("Alterar");        // TODO add your handling code here:
    }//GEN-LAST:event_tbVendasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows Classic".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmVendedorasTb013.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmVendedorasTb013.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmVendedorasTb013.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmVendedorasTb013.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmVendedorasTb013 dialog = new frmVendedorasTb013(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ITEM;
    public javax.swing.JButton btnCancela;
    private javax.swing.JButton btnCancelaLog;
    public javax.swing.JButton btnExcluir;
    public javax.swing.JButton btnIncluir;
    private javax.swing.JButton btnNovoLog;
    public javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnSalvarLog;
    private javax.persistence.EntityManager em;
    private javax.swing.JLabel idlojavendedorLabel;
    private javax.swing.JLabel idvendedorLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JComboBox<String> jcLoja;
    private javax.swing.JPanel jpBotoes;
    private javax.swing.JPanel jpDados;
    private javax.swing.JPanel jpLog;
    private java.util.List<com.guina.model.Tb013vendedoras> list;
    private java.util.List<com.guina.model.Tb010logsistema> listLog;
    private java.util.List<com.guina.model.Tb011lojas> listLoja;
    private java.util.List<com.guina.model.Tb001user> listUser;
    private javax.swing.JScrollPane masterScrollPane;
    private javax.swing.JScrollPane masterScrollPane1;
    private javax.swing.JLabel nomevendedorLabel;
    private javax.persistence.Query query;
    private javax.persistence.Query queryLog;
    private javax.persistence.Query queryLoja;
    private javax.persistence.Query queryUser;
    private java.util.List<com.guina.model.Tb013vendedoras> tb013vendedorasList;
    private javax.persistence.Query tb013vendedorasQuery;
    public javax.swing.JTable tbLog;
    public javax.swing.JTable tbVendas;
    private javax.swing.JTextField txtAcao;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtIdItem;
    private javax.swing.JTextField txtItem;
    private javax.swing.JTextField txtNome;
    public javax.swing.JTextField txtPesq;
    private javax.swing.JTextField txtTabela;
    public javax.swing.JTextField txtUser;
    public javax.swing.JLabel txtUsuario;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
///////////////FUNÇOES DO SISTEMA/////////////////////////////////
    //funçaõ pega o ultimo id e gera id para cadastro
    public void MaxId() {
        query = em.createQuery("SELECT t FROM Tb013vendedoras t ORDER BY t.idvendedor DESC");
        List<Tb013vendedoras> venda = query.getResultList();
        if (venda.size() == 0) {
            txtId.setText("1");
            novo = (Integer.parseInt(txtId.getText()));
        } else if (venda.size() > 0) {
            String args[] = new String[1];
            args[0] = venda.get(0).getIdvendedor().toString();
            n = (Integer.parseInt(args[0]));
            txtId.setText(Integer.toString(n));//Recupera o ultimo codigo
            novo = (Integer.parseInt(txtId.getText()) + 1);
        }
    }
    
    public void Dados() {
        //Dados para fazerlog
        Date data = new Date();
        SimpleDateFormat horaFormatada = new SimpleDateFormat("HH:mm:ss");
        SimpleDateFormat dataFormatada = new SimpleDateFormat("dd/MM/yyyy");
        //Pegar a hora
        txtHora.setText(String.valueOf(horaFormatada.format(data)));
        //Pegar a Data
        txtData.setText(String.valueOf(dataFormatada.format(data)));
        //Pegar tabela
        txtTabela.setText(tb);
        //Pega a ação
        txtAcao.setText(acao);
        //Pega o item
        txtIdItem.setText(txtId.getText());
        //Pega nome item
        txtItem.setText(txtNome.getText());
    }

    public void User() {
        int user = (Integer.parseInt(txtUsuario.getText()));
        queryUser = em.createQuery("SELECT t FROM Tb001user t WHERE t.iduser = :id ");
        queryUser.setParameter("id", (Integer.parseInt(txtUsuario.getText())));
        List<Tb001user> data = queryUser.getResultList();
        if (data.size() > 0) {
            String args[] = new String[1];
            args[0] = data.get(0).getNomeuser();
            txtUser.setText(args[0]);
        }
    }
}
